### ISSUE TITLE
John Kolesar

### ISSUE THREAD

**Issue by jckolesar** [cucapra/undergrad-research#10]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here is [an example](https://github.com/cucapra/undergrad-research/issues/1) of a filled out template for reference.

## Personal Details

**Name**:  John Kolesar

**Major**:  Mathematics and Classics

**Year in Cornell**:  Senior (Class of 2020)

**Relevant classes**:  CS 2112, CS 2800, CS 3110, CS 4820, CS 4110, CS 4850, MATH 4330, MATH 4140

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I want to do research in the Fall 2019 semester.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I've been looking for opportunities to do computer science research because I'm considering the possibility of doing a Ph.D. program in computer science after I graduate.  I've found the subject of programming languages interesting because of my experiences with CS 3110 and CS 4110.  I hope that I can further my understanding of the subject by working on a research project, and I also want to see whether I like the kind of work that a Ph.D. program involves.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
All of the Capra group's projects sound good to me.  I like being able to see the practical applications of the study of programming languages.

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
Recently I attended a thesis defense given by one of Professor Mimno's students about the examination of stylistic similarity in ancient Greek authors through the use of several different algorithms.  I haven't taken any courses previously on natural language processing, but I found the subject matter of the thesis appealing, especially because of the classics connection.

**Is there a specific grad student or a project you're interested in working on?**
I noticed that the Programming Abstractions for Natural Language & Intelligent Systems project relates to both programming languages and natural language processing, so that project seems like a good way to combine two of my interests.

**Anything else you want to tell us about yourself?**
In the fall of 2017, I worked as a consultant for CS 2112, and in the fall of 2018, I worked as a TA for CS 3110.

**Attach a CV if you like.**
[John C. Kolesar Resume June 2019.pdf](https://github.com/cucapra/undergrad-research/files/3248341/John.C.Kolesar.Resume.June.2019.pdf)

**Comment by Checkmate50** [comment]
Hey John, thanks for reaching out!  If you're still looking for a research project, I have a bit of an oddball project proposal.

We've been working for the last year on the Gator language for reasoning about geometric operations, particularly in computer graphics.  We're looking to develop a game engine in Gator, both to demonstrate that we can develop a large-scale graphics project in the language and to figure out what new problems need to be tackled.

While not an NLP project, there is work to be done on Gator as a research language, particularly in how we choose to represent ideas.  If this project sounds interesting, or if you want to hear more about Gator, let me know and I can forward you more information.

**Comment by jckolesar** [comment]
Thank you for letting me know about this.  The Gator project certainly sounds interesting, and I'd be glad to get more information about it.  However, I'm currently working for a different research group this semester, so I'm not sure how much work I could do for it at the moment.  What timeframe do you have in mind for the project?  Would it take place this semester or in an upcoming semester?

**Comment by Checkmate50** [comment]
That's great you found a research project!  We're laying out the groundwork for what I hope will become a larger project this semester, so I'm optimistic that this project will be running at least another year or two.  Beyond this particular development goal, Gator as a language could certainly be expanded in the future, which I hope will translate into future project ideas.

Since Gator is still a work in progress, I don't yet have a contained way to explain the project (I usually go into more detail during a meeting).  We are looking to submit a paper about Gator later this semester though; if you're interested, send me an email at dag368@cornell.edu and I could send you a rough draft of the paper when finished to explain more about the language.

**Comment by rachitnigam** [comment]
Since this thread has gone stale, I’m going to close it. @jckolesar if you’re still looking for research positions, please reopen it.
