### ISSUE TITLE
Stephen Verderame

### ISSUE THREAD

**Issue by stephenverderame** [cucapra/undergrad-research#105]
**Note.** Before applying, make sure you can receive notifications from Github. Once you apply, make sure you're subsribed to receive emails when someone responds to the issue. We will respond to your application on Github first so it's important that you receive notifications to it and respond quickly.

We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Stephen Verderame

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** 3rd year, early CS MEng. Planning to finish BS Fall 2023 and MEng Spring 2024

**Relevant classes**: CS 2112, CS 3110, CS 4120, CS 4160, ECE 4750, CS 4410, CS 4620, CS 4670

**Interested in continuing research during the summer?**
I have an internship for 2023, but potentially summer 2024

**Expertise (languages/frameworks/etc.):**
C++, C, Rust, Java, Python, OpenGL

## Research

**When do you want to do research?**
2023 - 2024 school year

**What is exciting to you about research?**
I'm really interested in working on tough problems in novel areas. I've had quite a few internships in industry, and I've always felt it would be exhilarating to be a part of something that doesn't just help customers, a team, a business unit, or even a company, but something that can be used by anybody and potentially create a path to something impactful. At the end of the day, industry is about turning a profit (which may well be a fact of life), and I'm interested in doing something different.

**What kind of research do you want to do?**
I'm open to anything, but I really enjoyed Compilers and Computer Architecture so probably something compilers related. I also have interest in formal verification.

## Background

**Was there a paper that particularly excited you?**
For the reasons mentioned below, the [Braid paper](https://dl.acm.org/doi/pdf/10.1145/3133895) really resonated with me, but so did the paper on Gator. In my most recent graphics project, I was plagued with errors due to mistmatched reference frames when implementing ray marched volumetrics. From my experiences with Coq, I've also been interested in using the type system to help ensure greater correctness. Gator kind of reminded me of a small header-only utility I made in C++ that used templates to encode units of values into the type system. So if a function expected a force parameter, you can't pass a length, but you could multiply a mass and acceleration, and then pass the result.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
I'm open to anything, but I am really fascinated by the work on Braid. As a kid, I got into CS from video games and have always enjoyed graphics. I've developed a few OpenGL projects, and everytime I write a GLSL shader, I can never help but brainstorm some ideas of a way to have a compiler that can take a single program and split up the different parts of it that will compile into CPU machine instructions and shaders on each of the different stages, without the explicit boilerplate for passing along data to different stages. 
More generally, I've always loved the idea of having an abstraction that can take a single source language and be able to introduce parallelism by having parts of it run on an accelerator.

Also, Gator is equally interesting to me as well, for reasons in the above answer. *To be clear, I am interested in more than just graphics related projects, but I suppose since I have some background in the area, these projects jumped out at me*.

**Anything else you want to tell us about yourself?**
I'm still technically an undergrad, but I was hoping to do research as my MEng project.

**Attach a CV/Resumé**
[My Resumé](https://drive.google.com/file/d/1R9AUOGrxIs2mqmoy6nLVWbBPiiNkjg-0/view?usp=sharing)

**Comment by Checkmate50** [comment]
Closing due to initial interest, feel free to re-open if you want others to take another look
