### ISSUE TITLE
Jeremy Ku-Benjet

### ISSUE THREAD

**Issue by jku20** [cucapra/undergrad-research#106]
## Personal Details
**Name**: Jeremy Ku-Benjet

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** 2nd Year with expected graduation Fall 2025 or Spring 2026

**Relevant classes**: CS 4120, CS 3410

**Interested in continuing research during the summer?**
Sure!

**Expertise:** OCaml, Java, Rust, C

## Research

**When do you want to do research?**
I am interested in starting in the coming semester(s). Depending if/how that progresses, I'd be interested in continuing during the summer.

**What is exciting to you about research?**
I'm excited by practical software tools to make it easier to solve problems in correct and performant ways.

**What kind of research do you want to do?**
I am interested in compiler building, but as much as anything in particular, I'm looking to explore!

## Background

**Was there a paper that particularly excited you?**
I recently read [Finding Missed Optimizations through the Lens of Dead Code Elimination](https://ethz.ch/content/dam/ethz/special-interest/infk/ast-dam/documents/Theodoridis-ASPLOS22-DCE-Paper.pdf). The main idea is a heuristic for testing compilers which is both very simple to understand (if a compiler outputs code another ones thinks is dead then maybe it should have removed it) and practical, an ever exciting combination. 

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
I find the Caiman project most interesting at a cursory look (however not sure if I have a good answer to the "why" part of the question), though I am interested in anything. 

**Anything else you want to tell us about yourself?**
I enjoy the occasional math problem.

**Attach a CV/Resumé**

**Comment by rachitnigam** [comment]
@jku20 please attach your CV as well

**Comment by jku20** [comment]
ah, sorry
here is a [link](https://jku20.github.io/extras/resume.pdf)

**Comment by Checkmate50** [comment]
Hey Jeremy!

I'm a PhD student working on Caiman, could you shoot me an email at dag368@cornell.edu if you're still interested so we can talk about a research idea?
