### ISSUE TITLE
Chris Lam

### ISSUE THREAD

**Issue by FlyingRockSquirrel** [cucapra/undergrad-research#11]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here is [an example](https://github.com/cucapra/undergrad-research/issues/1) of a filled out template for reference.

## Personal Details

**Name**: Chris Lam

**Major**: Computer Science and Math

**Year in Cornell**: Just completed sophomore year

**Relevant classes**: CS 1110/2110/2800/3110, MATH 1120/2210/2220/3340 (abstract algebra) /4710 (basic probability)

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
Fall 2019, and/or Summer 2019 if you still have any spots

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I've always enjoyed thinking about difficult problems and making efforts to solve them, and I often end up stumbling on a new one right as I need to focus on prelims or exams. I hope that being involved in research will help me learn how to approach the problems and questions involved in research in a more rigorous manner, potentially allow me to contribute to our greater body of scientific knowledge, and hopefully turn my main method of procrastination into productivity. 
EDIT: I forgot to mention that I'm also interested in grad school and I hope to get some research experience before I make that decision. 

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
Something to do with optimization, though I'm open to anything!

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
Though I'm still not at a level where I can fully understand it, Ross Tate's paper "Generalizing Compiler Optimizations from Proofs" was really interesting to me as it seemed to produce optimizations from drawing equivalences between programs. 

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[ChrisLam.docx](https://github.com/cucapra/undergrad-research/files/3259130/Resume.v3.docx)

**Comment by Checkmate50** [comment]
Hey Chris, thanks for reaching out!  If you're still looking for a research project, I have a bit of an oddball project proposal.  

We've been working for the last year on the Gator language for reasoning about geometric operations, particularly in computer graphics.  We're looking to develop a game engine in Gator, both to demonstrate that we can develop a large-scale graphics project in the language and to figure out what new problems need to be tackled.

If this project sounds interesting, or if you want to hear more about Gator, let me know and I can forward you more information.

**Comment by rachitnigam** [comment]
Since this thread has gone stale, I’m going to close it. @FlyingRockSquirrel if you’re still looking for research opportunities, please reopen it.
