### ISSUE TITLE
Jiahan Xie

### ISSUE THREAD

**Issue by jiahanxie353** [cucapra/undergrad-research#113]
**Note.** Before applying, make sure you can receive notifications from Github. Once you apply, make sure you're subsribed to receive emails when someone responds to the issue. We will respond to your application on Github first so it's important that you receive notifications to it and respond quickly.

We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Jiahan Xie

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** First year MS & Expected May 2025

**Relevant classes**: 3110, 3410

**Interested in continuing research during the summer?**: Yes it'd be great!

**Expertise (languages/frameworks/etc.):** Python, C++, Java, OCaml

## Research

**When do you want to do research?** 
I want to start on Fall 2023 and continue over next spring as a extracurricular; and summer as a full-time job if things go well.

**What is exciting to you about research?** 
I was researching machine learning (reinforcement learning, specifically) as in undergrad and gained a lot of experience in ML algorithms, NLP, CV, etc. At one point, I came to realize that the thrive of the applications in those fields rely extremely heavily on domain specific accelerators, parallel programming, etc. Then I learned about High-level Synthesis and got excited about automatic hardware accelerator generation. I then learned, however, that HLS tools can be very ad-hoc to certain software and hardware. 
To this end (and sorry for this lengthy motivation), I'm really interested in building compilers to fill the gaps between software and hardware design in ML to make it more generalizable and easier to optimize. 

**What kind of research do you want to do?**
Building compilers, that are more generalizable and friendly to programmers, easier for performance optimizations, for domain specific accelerators.

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
[Spatial: A Language and Compiler for Application Accelerators](https://dl.acm.org/doi/10.1145/3192366.3192379) really excites me. It strikes the balance between programmer productivity and accelerator's performance by providing hardware specific abstractions for tuning.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
Calyx. It's building an infrastructure that compiles high-level programs to domain specific hardware accelerators and demonstrates  efficient optimization. I'm also interested in Dahlia.

**Anything else you want to tell us about yourself?**
I really love music, especially classical music and lo-fi.

**Attach a CV/Resumé**
[Jiahan_Xie_Resume.pdf](https://github.com/cucapra/undergrad-research/files/12421564/Jiahan_Xie_Resume.pdf)

**Comment by rachitnigam** [comment]
Hi @jiahanxie353! Out of curiosity: are you looking for an MS project (is this a thing?) or just be involved in research? The processes for these are slightly different (at least for MEng project) so would be useful to know.

**Comment by jiahanxie353** [comment]
Hi @rachitnigam ! I want to be involved in research in Capra! 
While there isn't a thing as an "MS project", we do need to take CS 7999 for MS research thesis, which isn't super important right now and we can discuss about this later. Right now I'm just a student enthusiastic about compiler design and want to get involved :)

**Comment by rachitnigam** [comment]
Sounds good! I'm the project lead for Calyx and we're looking for someone to work on the Calyx CIRCT project to [build a new, completely open-source high-level synthesis toolchain](https://github.com/cucapra/calyx/issues/1680).

The project requires a fair bit of understanding of C++ and using the [LLVM/MLIR toolchains](https://mlir.llvm.org/) and a lot of independence on your part. If that is something you're interested in, we can discuss a small project to start off with to figure out if a long-term research position would work. For example, here [an issue](https://github.com/llvm/circt/issues/4843) that will help you familiarize yourself with the CIRCT codebase and learn how to implement some cool compilers stuff. Beware that this is definitely throwing you into the deep end of things so feel free to ask us questions if you take it up.

**Comment by jiahanxie353** [comment]
Sounds good to me! I'm fairly comfortable with C++ but still need to catch up LLVM/MLIR toolchains. But I definitely would love to take one small project to start off!

**Comment by jiahanxie353** [comment]
Sure I will! Just to clarify, is right now more like exploring Calyx, and is there any specific outcome expected for this step?

**Comment by jiahanxie353** [comment]
Hi @rachitnigam! So I've been learning LLVM and MLIR, and walking through Calyx paper and documentation for the past weeks. I found LLVM/MLIR to be too huge to learn in a short term. Therefore I was wondering, while I will continue to be learning them, it'd be great if you could also point me to some specific resources to solve the aforementioned issue! Thanks!

**Comment by rachitnigam** [comment]
Hey @jiahanxie353! Thanks for reaching out. That seems totally reasonable–MLIR is a complex infrastructure so it takes a while to get used to it. One thing to do here is commenting on the issue saying that you'd like to take it up and ask for some direction. A couple of places to look is starting with the minimal reproducible example provided in the issue and seeing if you can at least trigger the same error message.

Next, I think you'll have to understand the structure of the `CalyxToSCFPass` file and how the [`scf` dialect][scf] works. Specifically, the problem is that [`scf.yield`][yield] can occur inside both `scf.while` and `scf.if` and the pass assumes that they only occur within `scf.while`.

Once you have some understanding of the problem, I think you can try proposing an approach to the solution and getting some feedback from the folks in the issue. There is also a [discord for LLVM][llvm] which has a CIRCT channel where people might be able to help.

Take a shot at this and send me an email at the end of next week to schedule some time to virtually chat!

[scf]: https://mlir.llvm.org/docs/Dialects/SCFDialect/
[yield]: https://mlir.llvm.org/docs/Dialects/SCFDialect/#scfyield-scfyieldop
[llvm]:  https://lists.llvm.org/pipermail/llvm-dev/2019-November/136880.html

**Comment by jiahanxie353** [comment]
Thank you so much for sharing! Will do!
