### ISSUE TITLE
Cassandra Sziklai

### ISSUE THREAD

**Issue by csziklai** [cucapra/undergrad-research#118]
**Note.** Before applying, make sure you can receive notifications from Github. Once you apply, make sure you're subsribed to receive emails when someone responds to the issue. We will respond to your application on Github first so it's important that you receive notifications to it and respond quickly.

We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Cassandra Sziklai

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** Undergrad junior, May 2025

**Relevant classes**: CS 2110, CS 3110

**Interested in continuing research during the summer?** Possibly

**Expertise (languages/frameworks/etc.):** Ocaml, Java, Python, HTML/CSS, D3.js

## Research
**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular", equivalent to a 3-4 credit class, or get more involved over the summer as a full-time job.)
I would like to get started in the spring, and potentially stay over the summer for research.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I am excited at the possibility of exploring new frontiers of computer science. I love problem-solving and thinking algorithmically and want to apply what I’ve learned to helping make advances in the field.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
While I’m still exploring my interests, I think I’d like to head in the direction of programming languages design. Taking CS 3110 and learning Ocaml has broadened my perspective on programming beyond any specific language. I would love to learn more.

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
A paper that I like is "Monads for Functional Programming" by Philip Wadler. It is interesting to see how features I take for granted in functional languages such as Ocaml, were developed and reasoned about. I think it is such an elegant solution to the problems described of needing a way to keep track of a certain state relevant in the global scope.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
I would be interested in working on Dahlia, but am flexible. Working on the development of a programming language and reasoning about tradeoffs sounds fascinating.

**Anything else you want to tell us about yourself?**
I would be a dedicated research assistant and what I lack in experience, I make up for with drive and passion.

**Attach a CV/Resumé**
[Cassandra Sziklai resume 2023 compressed.pdf](https://github.com/cucapra/undergrad-research/files/13379367/Cassandra.Sziklai.resume.2023.compressed.pdf)

**Comment by rachitnigam** [comment]
Hey @csziklai! Can you drop me an email at rnigam@cs.cornell.edu and we can set up some time to chat?
