### ISSUE TITLE
Ethan Uppal

### ISSUE THREAD

**Issue by ethanuppal** [cucapra/undergrad-research#120]
**Note.** Before applying, make sure you can receive notifications from Github. Once you apply, make sure you're subsribed to receive emails when someone responds to the issue. We will respond to your application on Github first so it's important that you receive notifications to it and respond quickly.

We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Ethan Uppal

**Major**: CS (+ maybe ECE)

**Year in Cornell & Expected graduation date:** Freshman, expecting 2027

**Relevant classes**: CS 2110 and 2800. Self-studied CS 3110. Self-studying 4820 over the winter. Very familiar with 3410.

**Interested in continuing research during the summer?**: Yes!

**Expertise (languages/frameworks/etc.):** C, C++, Swift, x86 Assembly, and various other languages. I have made an optimizing compiler from scratch in both C and C++. I [have also reverse-engineered](http://ethanuppal.github.io/reverse/) Apple's executable file format.

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular", equivalent to a 3-4 credit class, or get more involved over the summer as a full-time job.)

I think summer would be the best, but I can be flexible :)

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)

Over the last summer, I did research in a quantum optics lab. It was very cool to learn the rigorous theory behind concepts like quantum entanglement and apply it in experiments. Physics research was fun and rewarding, but now that I am thinking about CS grad school, I want to try to get experience in CS research, especially in the area I want to specialize in (PL). 

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")

I haven't had any prior opportunities in CS research, so I am open to anything, but I am especially interested in proving correctness in hardware (see the background section).

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

I read [Static Program Analysis](https://cs.au.dk/~amoeller/spa/spa.pdf) by Møller and Schwartzbach a couple of years ago, which sparked my interest in PL. I especially liked the section on sign analysis through lattices, and I (unsuccessfully) tried to incorporate it into the compiler I was then building. Recently, I discovered CAPRA and read the group's paper on Gator. I was very impressed by the idea of using the type system to enforce the correctness of geometric transformations. 

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**

It is hard to choose because everything seems so cool! If I were pressed, I would want to focus on the hardware-adjacent side. I have been able to explore compilers and graphics programming in personal projects before, so researching in hardware would give me an opportunity to learn in a field I am growing increasingly interested in. Filament especially among the hardware projects looks really awesome in how it can enforce physical properties of your system just through type-checking.

**Anything else you want to tell us about yourself?**

I am an ardent supporter of the No-Pineapple-On-Pizza movement. I like playing piano and studying linguistics in my free time. I do not put my braces on new lines.

**Attach a CV/Resumé**
[Ethan Uppal Resume.pdf](https://github.com/cucapra/undergrad-research/files/13747325/Ethan.Uppal.Resume.pdf)

**Comment by rachitnigam** [comment]
Hey @ethanuppal, can you email me at rnigam@cs.cornell.edu and we can set up some time to chat?

**Comment by ethanuppal** [comment]
Done :)

**Comment by ethanuppal** [comment]
Hello! Just following up on this — I am still interested in research if any opportunities are available, and I'm open to work on any project.

**Comment by anshumanmohan** [comment]
Closing this issue since you are working with us this summer!
