### ISSUE TITLE
Yuyi He

### ISSUE THREAD

**Issue by yuyihe** [cucapra/undergrad-research#13]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: Yuyi He

**Major**: Electrical and Computer Engineering

**Year in Cornell**: 2022

**Relevant classes**:
• Introduction to Computing Using Python
• Object-Oriented Programming and Data Structures (Fall 2019)
• Introductory Design and Programming for the Web
• Intermediate Design and Programming for the Web
• Digital Logic and Computer Organization (Fall 2019)
• Embedded Systems (Spring 2020)

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
During the semesters and winter break too if possible 

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I am interested in research because I am eager to learn more about Computer Architecture outside of the classroom. I am passionate about the trade offs between out-of-order execution paradigm used in most computers nowadays and the potential security problems it may bring. I am also passionate about increasing the processing efficiency of computers while doing it at a low energy cost. 

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
1. Something that addresses the trade offs between out-of-order execution paradigm used in most computers nowadays and the potential security problems it may bring.
2. Something that addresses the conflicts between processor efficiency and energy waste.

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
No, but I went to Professor Adrian Sampson's tech talk at Gates Hall in July and that talk excited me. The talk was about the evolution of computer architecture and how the design has evolved so the computers can have a higher processing efficiency. The talk then addressed the security problems that came with this evolution and talked about the typical trade offs between efficiency and energy. This talked got me excited for the future of computer architecture and I am eager find out a solution to address these issues by doing some research.

**Is there a specific grad student or a project you're interested in working on?**
No

**Anything else you want to tell us about yourself?**
I was first introduced to computer architecture in ECE 1210 and I instantly fell in love with it. I am excited to learn more about computer architecture in the future.

Also I like ice cream a lot! :)

**Attach a CV if you like.**
[Yuyi_He_Resume.pdf](https://github.com/cucapra/undergrad-research/files/3490337/Yuyi_He_Resume.pdf)

**Comment by sampsyo** [comment]
Hi, Yuyi! Thanks for getting in touch. It would be great to discuss potential research collaborations. Can we get in touch with you a few weeks into the semester? (Be sure to remind us if we forget!)

**Comment by yuyihe** [comment]
Hi Prosessor Sampson,

Thank you so much for getting back to me!

Yes, I would love to discuss some potential research collaborations. Would
the weekend of September 14-15 or September 21-22 work for you? (I can do
weekdays too but my schedule is kind of crazy with all the classes haha)

Thanks again. I’m looking forward to meeting you!

Sincerely,
Yuyi

**Comment by sampsyo** [comment]
Actually, would it be OK with you if we hold off for a few weeks to schedule a meeting? That will help give us some time to think about appropriate projects (and with whom it would be most useful to talk to).

Also, I appreciate that your weeks are busy, but I don't think it can feasibly be a weekend. We're not normally on campus then. :)

**Comment by yuyihe** [comment]
Of course!

Sorry for rushing it😅 and sure weekdays could work for me.

Thank you so much!

Sincerely,
Yuyi

**Comment by sampsyo** [comment]
Hi, Yuyi! Sorry for dropping the thread a while back, but I'm curious if you're still interested in research for the spring semester. We have a new project about implementing machine learning workloads on a novel, open-source, massively parallel processor. Let me know if you're interested and we can set up a meeting.

**Comment by yuyihe** [comment]
Hi Professor Sampson,

Thank you so much for getting back to me!

I am still interested in research, but I don't know if I am able to handle my current workload for the spring semester yet. I am definitely open to set up a meeting with you and discuss about it further though.

Thank you!

Sincerely,
Yuyi

**Comment by sampsyo** [comment]
Great! I'll send you an email out of band.

**Comment by rachitnigam** [comment]
I assume @yuyihe met with @sampsyo for research. @yuyihe if you’re still looking for research positions, please reopen the issue. If not, good luck with everything!
