### ISSUE TITLE
Skye Slattery

### ISSUE THREAD

**Issue by skyeslattery** [cucapra/undergrad-research#132]
## Personal Details

**Name: Skye Slattery**

**Year in Cornell: Freshman**

**Relevant classes: CS 2110, CS 2800 (current), CS 3110 (current), MATH 2940 (current) **

**Expertise (languages/frameworks/etc.): Java, Python, SQL, Flask, some C++, some JavaScript, some C#.**

## Research

**When do you want to do research?**
I am eager to get started learning as soon as I can, so during this semester would be best. That being said, I live in Ithaca and am looking for a summer research experience, so ultimately I would love to be able to be a part of a summer project. 

**What is exciting to you about research?**
Upon coming to Cornell, I knew immediately that I wanted to get into research. Being able to become one of the most knowledgeable people in the world in a specific topic, and learning as much as I can about it, learning through failures and triumphs and exploring new ideas is extremely exciting to me. Last semester, I had the pleasure of working with incoming professor  Saikat Dutta on a small research project, where I learned about software testing and wrote a plugin for python that would allow rerunning flaky tests multiple times, giving more insight into the issue than just a simple test failure. Ultimately, we didn't pursue further research because working remotely was difficult for me and I wanted to explore a more formal lab experience. However, the experience was great, and made me even more excited to get into research.

**What kind of research do you want to do?**
I would be excited to do work with graphics, anything to do with unique programming languages, and perhaps a bit of math!

## Background

**Was there a paper that particularly excited you?**
A paper I love is a famous one: [Why Functional Programming Matters](https://www.cs.kent.ac.uk/people/staff/dat/miranda/whyfp90.pdf) by John Hughes. CS 3110 in functional programming made me think question the importance of functional programming when, at the beginning, I found it much harder to do simple tasks in functional languages. That led me to this paper, which helped me answer that question. I love the idea that learning a new language/group of languages teaches you something about becoming a better programmer, and that paper helped me recognize the work I was doing was not in vain.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
Two projects that really interest me are "Geometry Types for Graphics Programming in Gator", and "Reconfiguring the Imaging Pipeline for Computer Vision" as they match my interests very well, but I would be ecstatic to try anything.

**Anything else you want to tell us about yourself?**
I love to get creative, work well with other people, and pick up new things quickly. I hope being a freshman will not prevent you from overlooking my enthusiasm to learn, deep interests in the topics, and friendliness. It would be amazing to work with you!

**Attach a CV/Resumé:**
[resume-2-24.pdf](https://github.com/cucapra/undergrad-research/files/14551845/resume-2-24.pdf)

**Comment by skyeslattery** [comment]
Still interested for Fall 2024 and/or anything for the remainder of the
summer.

**Comment by sampsyo** [comment]
Thanks, Skye; we'll keep you in mind for the fall!
