### ISSUE TITLE
Kofi Amoako Efah

### ISSUE THREAD

**Issue by Kofi-A-Efah** [cucapra/undergrad-research#14]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: Kofi Efah

**Major**: Electrical and Computer Engineering

**Year in Cornell**:  Rising Sophmore (Expected graduation in 2022)

**Relevant classes**: 
CS 1110 - Introduction to Computing in Python
ECE 1210 - Computing Technology in your Smartphone
ECE 2400 - Computer Systems Programming(For Fall 2019)
ECE 2300 - Digital logic and Computer Organization (For Fall 2019)

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)

It would be ideal if I could get into research during the fall semester, but the spring semester is also a definite possibility.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I first considered research after realizing my passion for Computer Architecture and VLSI design methodologies. After taking ECE 1210, I fully realized my desire to contribute to such projects to obtain an understanding of Computer Architecture as we know it today beyond the confines of a classroom setting. This became the driving force that prompted me to learn C, a low-level programming language, on my own time.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I am interested in research investigating the trade-offs between energy, efficiency and other outlying factors in computers, and hardware-software abstractions.

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
Professor Albonesi's research on Power and Reliability-Aware Computing particularly interests me, specifically his paper, "Dynamic GPGPU Power Management Using Adaptive Model Predictive Control."
**Is there a specific grad student or a project you're interested in working on?**
Nothing in particular
**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[Kofi Efah Resume.pdf](https://github.com/cucapra/undergrad-research/files/3522730/Kofi.Efah.Resume.pdf)

**Comment by sampsyo** [comment]
Hi there! I'm glad you're interested in doing some low-level hacking! Do you mind if we take a little time to see what might be going on during the fall semester and get back to you? Things are still taking shape for now, but there might be something that comes up that would be a good match.

**Comment by Kofi-A-Efah** [comment]
That sounds just fine, Professor Sampson!

**Comment by sampsyo** [comment]
Hi again! Sorry for dropping the thread a while back, but I'm curious if you're still interested in research for the spring semester. We have a new project about implementing machine learning workloads on a novel, open-source, massively parallel processor. Let me know if you're interested and we can set up a meeting.

**Comment by Kofi-A-Efah** [comment]
Hello! I’m definitely, interested in research, but I am not sure how it would fit in my current spring schedule. We can set up an appointment and talk about it further!

**Comment by sampsyo** [comment]
Great. I'll send you an email.

**Comment by rachitnigam** [comment]
I assume @Kofi-A-Efah met with @sampsyo. @Kofi-A-Efah if you’re still looking for research opportunities, please feel free to reopen the issue!
