### ISSUE TITLE
Nikil Shyamsunder

### ISSUE THREAD

**Issue by Nikil-Shyamsunder** [cucapra/undergrad-research#143]
## Personal Details

**Name:** Nikil Shyamsunder

**Undergrad or MEng?** Undergrad

**Year in Cornell:** Sophomore

**Relevant classes:**
CS 2110, CS 2800, Math 2210 (Linear Algebra), CS 3110 (currently), CS 4820 (currently), CS 3410 (Next Sem), CS 3780 (Next Sem)

**Expertise (languages/frameworks/etc.):**
Python, Java, OCaml, HTML, CSS, JS/React, SQL, Unix, NumPy, Pandas, TensorFlow, Agile, Git

## Research

**When do you want to do research?**

I'd like to start this Fall (2024), continue on through the years I have at Cornell, and maybe even spend a summer here doing research.

**What is exciting to you about research?**
The thrill of tackling problems without predefined answers pushes me to think critically and creatively. I love how research lets us build on existing knowledge by "standing on the shoulders of giants," as Newton said, but also gives us the freedom to question everything. This lab’s focus on "rethinking hardware–software abstractions" aligns perfectly with my passion for challenging conventional boundaries and exploring the interactions between different abstraction levels in computing.

**What kind of research do you want to do?**
I've had the opportunity to work on various projects in machine learning, Edge AI, and web development in the past—areas that operate at a relatively high level of abstraction. While I found these projects engaging, I've always been drawn to the deeper, more fundamental aspects of computing. My interest has shifted to working in a more systems-y area; I find the tangled interactions between various levels of "thinking" in a computer system, from bits all the way to high-level programming languages to be quite interesting. While I still have much to learn in this area, the prospect of exploring these interactions and contributing to this field excites me immensely.

## Background

**Was there a paper that particularly excited you?**
I recently read your paper, "Unifying Static and Dynamic Intermediate Languages for Accelerator Generators," and found your approach to combining static and dynamic control in a single framework to be incredibly intriguing. Though I admittedly am not yet deeply versed in this area, given my nascent interest in programming languages, compilers, and systems-y work, the methods and various fields of CS brought together to implement Piezo was quite compelling.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
I am particularly interested in the Hardware Accelerator Generation and Graphics Programming projects within CAPRA. Past that, all of the specific projects are fascinating, but my past experiences and domain knowledge don't strongly point to a specific preference.

**Anything else you want to tell us about yourself?**
When I was a kid, my dad used to tell me stories about Brian Kernighan, Linus Torvalds, and James Gosling as our very nerdy superheroes. In high school, I got the courage to send what was essentially "fan mail" to Kernighan's Princeton email... and he actually responded! One of the coolest moments of my life.

Here's my website: [https://www.nikilshyamsunder.com/](https://www.nikilshyamsunder.com/)

**Attach a CV/Resumé:**
[Shyamsunder-Nikil-Resume-cucapra.pdf](https://github.com/user-attachments/files/16842468/Shyamsunder-Nikil-Resume-cucapra.pdf)

**Comment by sampsyo** [comment]
Hi, @Nikil-Shyamsunder—I imagine it's quite likely that you've found other interesting research to do in the intervening time, but I'm starting to look for some possible collaborators on a project about genomics processing. To be totally transparent, I originally tried recruiting MEng students at the beginning of the semester and got no bites—but I did write up this description of where we're going:
https://capra.cs.cornell.edu/notes/pollen-meng.html

Anyway, you can obviously ignore the MEng-related stuff in there. Any chance this might appeal? If not, no big deal—I'm sure there will be other projects available sometime soon. Let me know if you're interested and we can chat.

**Comment by ekiwi** [comment]
Nikil is actually working with me now :)
