### ISSUE TITLE
Katerina Sadov

### ISSUE THREAD

**Issue by ksadov** [cucapra/undergrad-research#15]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: Katerina Sadov

**Major**: Computational Biology, with the intent to pursue a PhD in Computer Science.

**Year in Cornell**: Senior

**Relevant classes**:
CS 3110 Data Structures and Functional Proramming
CS 3410 Systems Programming
CS 4160 Formal Verification
CS 2800 Discrete Structures
MATH 2210 Linear Algebra
Math 2220 Multivariable Calculus
BIONB 3330 Introduction to Computational Neuroscience

## Research

**When do you want to do research?**
Fall 2019, Spring 2020 and possibly Summer 2020.

**What is exciting to you about research?**
I did computational neuroscience research at the Goldberg Lab at Cornell for two years. I enjoyed reading papers to deepen my knowledge and look for open research questions, designing and setting up experiments, and analyzing data to answer questions and inspire new ones. I realized that I was primarily interested in the computer science aspects of my work, and hope to deepen my understanding of the field by working in a wholly CS-focused lab.

**What kind of research do you want to do?**
I worked with machine vision and convolution neural networks during my time at the Goldberg lab, so I would be interested in working on a related project. Taking CS 3410 and thinking about the analogies between neural circuits and digital circuits got me excited about hardware, so I would also enjoy the opportunity to do low-level work.

## Optional Stuff

**Was there a paper that particularly excited you?**
An implementation of the Zero Instruction Set Computer (ZISC036) on a PC/ISA-bus card, 1994
( http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.31.8540&rep=rep1&type=pdf ) opened my eyes to how hardware can be manipulated to optimize for specific processes. I was particularly intrigued by how a system so different from the RISC architecture that we learned about in CS 3410 could be useful in modeling neural networks.

I found Capra’s paper “Reconfiguring the Imaging Pipeline for Computer Vision” appealing because of my own experience working with computer vision in the Goldberg Lab. It was interesting to consider how much of an image does not contribute to object recognition and detection, and how forgoing these aspects makes computer vision more energy-efficient.

JANUS: A Time-Reversible Language, 1986 (http://tetsuo.jp/ref/janus.pdf) is a short description of a language designed to support deterministic forward and backwards computation. Although it was not designed for serious use, I liked how it applied principles of programming language design to accomplish a slightly esoteric goal.

**Is there a specific grad student or a project you're interested in working on?**
I am particularly interested in Fuse, but would be happy to work on any project.

**Attach a CV if you like.**
[currentresume.pdf](https://github.com/cucapra/undergrad-research/files/3538582/currentresume.pdf)

**Comment by sampsyo** [comment]
Hi, Katerina! Thanks for getting in touch. It seems like there might be a good match somewhere in our group, but we're still ramping up for the semester—can we get back to you in a week or two as things get going?

**Comment by rachitnigam** [comment]
Hi @ksadov, since this thread has been stale for a while, I’m going to close it. If you’re still looking for research opportunities, feel free to reopen it. If not, good luck with everything else!
