### ISSUE TITLE
Kimberly Baum

### ISSUE THREAD

**Issue by kimberlybaum** [cucapra/undergrad-research#16]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: Kimberly Baum

**Major**: Information Science, Concentration in Interactive Technologies

**Year in Cornell**: Second Semester Junior (graduating winter 2020)

**Relevant classes**:
CS 2110
INFO 2300
INFO 2450
INFO 2950
INFO 4900
Current: INFO 4320, INFO 4340

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)

Fall and/or spring semester 2019-2020.  If all goes well, I would consider staying at Cornell for research next summer.

**What is exciting to you about research?**

I was involved in research last semester and it reignited my interest in CS. I enjoy the creativity involved in exploring on problems which have not been solved yet. 

**What kind of research do you want to do?**

I'm open to anything, but I always lean towards projects which involve a visual/artistic component. 

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[klb282.pdf](https://github.com/cucapra/undergrad-research/files/3560960/klb282.pdf)

**Comment by Checkmate50** [comment]
Hey Kimberly, thanks for reaching out!

We have an ongoing project to develop a language for graphics programming.  [Gator](https://github.com/cucapra/linguine) (previously Linguine) is a language designed to reason about geometric operations, which rely on frames of reference and underlying coordinate representations.  We would like to both use Gator to develop new graphics tools (such as a game engine) to better understand how the language works, and to develop tools for reasoning about the geometric types introduced by Gator.  If working on Gator or either of these projects sounds interesting to you, let me know so we can discuss these or other ideas.

**Comment by kimberlybaum** [comment]
Hi Dietrich, 

Thank you for getting back to me! This project seems really interesting and I would love to speak more about it with you. I am available any time outside of 11:00 am-4:30 pm Mon-Thur. 

Best,

Kim
klb282@cornell.edu

**Comment by Checkmate50** [comment]
Hey Kim,

Great!  If you're on campus tomorrow, I'm free 10-2 and could meet at, say 1pm.  If not, then 10 am any day T-Th next week would work for me.  Do any of those times work well for you?

Also, feel free to email me directly at dag368@cornell.edu rather than replying to this post for scheduling a time.

Cheers,
Dietrich
