### ISSUE TITLE
Katy Voor

### ISSUE THREAD

**Issue by kavoor** [cucapra/undergrad-research#17]
## Personal Details

**Name**: Katy Voor

**Major**: Computer Science

**Year in Cornell**: 4th year

**Relevant classes**: CS4120, ECE4750, CS3410, CS4410

## Research

**When do you want to do research?**
This semester and into the spring as well.

**What is exciting to you about research?**
After taking Compilers last spring and Computer Architecture last fall, this is definitely the place I want to be.

Over the summer, I had the privilege of working on the Hacklang compiler/HHVM. This involved working across the stack from parsing/typechecking to runtime support (JIT/ Interpreter). I also attained some exposure to programming language design through discussing with peers and investigating new features by comparing prior art in Kotlin, Scala, and Rust. I then presented these language feature proposals at the weekly Hacklang Design Discussions. I would like to continue working on a team on PL/Computer Architecture/Compilers projects. The more I learn, the more I want to learn.

**What kind of research do you want to do?**
I'm open to exploring projects in this space, but am particularly interested in building compilers, designing programming languages, or working at the computer architecture level. 

## Optional Stuff
**Was there a paper that particularly excited you?**
[Integrating Typed and Untyped Code in a Scripting Language](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.175.4207&rep=rep1&type=pdf) This paper discusses *like types*, an intermediate type between dynamic and static typing. Like types allow for untyped and typed code to coexist, and this knowledge can be used to precisely tell the runtime which checks need to happen. This paper presents the concept of a *dynamic type*, or a type with no static checks. It presents *concrete types*, types guaranteed to refer to an instance of that type or one of its subtypes. Finally, it presents the notion of a *like type*. Like types combine static and dynamic checking by statically checking all manipulations of that variable and performing runtime checks to all uses of the value bound to that variable. This information allows the runtime additional knowledge to save time checking types we can prove, as well as maintaining some flexibility.

I enjoyed this paper as I hadn't thought about type annotations as a way to tune runtime behavior. It made me think more about some of the differences in the compilers of statically-typed languages and dynamically typed ones.

**Attach a CV if you like.**
[cvFall2019](https://github.com/cucapra/undergrad-research/files/3577466/output.7.pdf)

**Comment by avanhatt** [comment]
Hi Katy, thanks for reaching out! 

We have an ongoing project using program synthesis to optimize the hardware/software boundary for programs in LLVM’s intermediate representation. There are several components of working on this compiler that might be of interest to you, from developing a better automated cost model for LLVM instructions to thinking more broadly about how we might support incremental compilation. Let me know if this sounds interesting, and we can arrange a time to meet to discuss these and other potential ideas.

**Comment by kavoor** [comment]
Hi Alexa! I'm very interested in learning more about this project. I'm available T/TH after noon and MW 11-1, after 4, and F after 2:30. Let me know if any of these times are convenient for you.

Thanks!

**Comment by avanhatt** [comment]
Great! Just sent you an email.
