### ISSUE TITLE
Palini Ramnarayan

### ISSUE THREAD

**Issue by paliniram16** [cucapra/undergrad-research#19]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: Palini Ramnarayan

**Major**: Computer Science

**Year in Cornell**: Junior

**Relevant classes**: CS 1133, CS 2110, CS 3110, CS 3410, Foundations of Computer Graphics (edX online course). Currently taking CS 4620 and CS 4621.

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I'd like to get involved this semester if possible, and I'm also open to spending some time over the summer to get a more immersive research experience.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I regard research as an opportunity to look more deeply into a topic that interests me. I’ve always been someone who loves to learn and think critically about what I already know. Research will allow me to apply my love of learning towards a larger project. The chance to discover new things, be they large or small, is always something I have found exciting. I also just want to know if research is something that is right for me; I've been thinking about grad school and know that doing research is a large part of it. 

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I’d like to do research related to computer graphics and/or computer vision. One of my greatest passions growing up was art, so I always look for ways to apply computer science to interdisciplinary areas such as graphics. While I think the current graphics programming languages are powerful and highly effective, I also feel that a lot can be done to improve them. For example, glsl is a difficult language to debug because most errors are caught at runtime. The provided error messages can also be convoluted and hard to understand. I’d love to do research that explores ways of improving graphic software. 

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
Braid was a project that really stood out to me. Heterogeneous programming is a topic that’s new to me, and I find it exciting to see an application to computer graphics. Having worked with OpenGL and glsl, I’ve experienced the drawbacks of each language. It was hard to know, as I changed my code, how the result would end up looking. Being able to see the results in real-time would have been extremely useful, and also would have made the process quicker. I also appreciate that Braid gives the developer control of which language they want to program in. This gives the language a solid structure while still allowing for freedom and flexibility. 

**Is there a specific grad student or a project you're interested in working on?**
I’m interested in working with Deitrich Geisler on developing the Gator language. As mentioned in my other answers, I’m extremely interested in computer graphics and I would love to learn more about how to design a graphics programming language. 

**Anything else you want to tell us about yourself?**
By far my favorite project that I completed in my coursework at Cornell was implementing an interpreter in OCaml. I loved digging into the nuts and bolts of how programming languages work and learning how to implement different functionalities. The Capra research group presents a unique opportunity for me to learn more about how programming languages are built while actively applying them to computer graphics. I would love any chance to get involved. 

**Attach a CV if you like.**

**Comment by Checkmate50** [comment]
Thanks for reaching out!  I've sent an email with details about a meeting time and some initial readings.
