### ISSUE TITLE
Akshat Singh

### ISSUE THREAD

**Issue by aksinh** [cucapra/undergrad-research#20]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: Akshat Singh

**Major**: Computer Science

**Year in Cornell**: Senior

**Relevant classes**: 3110, 4820, CS 4999 with Professor Nate Foster

## Research

**When do you want to do research?**
This semester

**What is exciting to you about research?**
My first opportunity to do research was with Professor Sampson in Sophomore Spring and what I really enjoyed was getting to tackle an open question and come up with my own approach and design to it. I also have always been interested in the more theoretical side of Computer Science and I fell research gives the opportunity to see how those concepts are applied to something meaningful in a more real way than any job in the tech industry.

**What kind of research do you want to do?**
I'm looking to explore. Last semester I got to work with Professor Foster on the NETKAT language and successfully implemented Angluin's L* learning algorithm for automata learning in OCaml. Something similar to that would be cool but no particular preference.

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
I really enjoyed reading `NetKAT: Semantic Foundations for Networks` and finding out how the interpreter logic and semantics we learnt in CS 3110 could be applied to building a network programming language

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[Resume (1).pdf](https://github.com/cucapra/undergrad-research/files/3591966/Resume.1.pdf)

**Comment by Checkmate50** [comment]
Hey Akshat, thanks for reaching out!  If you're still looking for a research project, I have a bit of an oddball project proposal.  

We've been working for the last year on the Gator language for reasoning about geometric operations, particularly in computer graphics.  We're looking to develop a game engine in Gator, both to demonstrate that we can develop a large-scale graphics project in the language and to figure out what new problems need to be tackled.

If this project sounds interesting, or if you want to hear more about Gator, let me know and I can forward you more information.

**Comment by rachitnigam** [comment]
Since this thread has gone stale, I’m going to close it. @aksinh if you’re still looking for research opportunities, feel free to reopen it.

**Comment by aksinh** [comment]
Hi Rachit, sorry seems I missed the notification last semester about this. Are there any research opportunities open this semester? I would still be interested

**Comment by rachitnigam** [comment]
Not sure if @Checkmate50 is still looking for students. I'm going to reopen it in case someone else is.

**Comment by Checkmate50** [comment]
Hey @aksinh.  If you're still interested in research, send me an email at dag368@cornell.edu, and I can follow up with some details on Gator.  I'm looking more for compiler work at the moment, which you might be interested in.
