### ISSUE TITLE
Yingying Yu

### ISSUE THREAD

**Issue by Yingyingyu0801** [cucapra/undergrad-research#21]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: Yingying Yu

**Major**: Computer Science

**Year in Cornell**: Master of Engineering (expected graduate May 2020, but can extend to December 2020 if needed)

**Relevant classes**: CS2110, CS3110, CS3410, CS4410

## Research

**When do you want to do research?**
 I would love to start with research in Fall 2019.

**What is exciting to you about research?**
It's exciting for me to learn new technologies between software engineering and hardware design. If I'm still interested after I go deeper into the research, I might consider pursuing a ph.D degree after that.

**What kind of research do you want to do?**
I have no idea yet but I'm looking to explore!

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
Not yet but I will look into more papers in the following weeks.

**Is there a specific grad student or a project you're interested in working on?**
I'm interested in anything and would love to help with any on-going project.

**Anything else you want to tell us about yourself?**
I'm passionate about doing research and would love to explore some of my research interests to finally decide my field. I will dedicate and put efforts on it!

**Attach a CV if you like.**
https://www.dropbox.com/s/h3n6bvx9djm3978/resume_YingyingYu.pdf?dl=0

**Comment by sampsyo** [comment]
Hi, Yingying! Sorry for the late response, but I'm curious if you're still interested in research for the spring semester. We have a new project about implementing machine learning workloads on a novel, open-source, massively parallel processor. Let me know if you're interested and we can set up a meeting.

**Comment by Yingyingyu0801** [comment]
﻿Hi Andrian,

I’m interested but I will arrive in town late until Jan 29th. Can we set up a meeting 
after next Tuesday? Thank you very much!



Best,
-- 
Yingying Yu

**Comment by sampsyo** [comment]
Sounds good! I'll send you an email.

**Comment by rachitnigam** [comment]
I assume @Yingyingyu0801 and @sampsyo met. @Yingyingyu0801 if you are still looking for research opportunities, please reopen it!
