### ISSUE TITLE
Andrew Pareles

### ISSUE THREAD

**Issue by andrewpareles** [cucapra/undergrad-research#22]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**:
Andrew Pareles (amp342)

**Major**:
CS (Physics minor)

**Year in Cornell**:
3rd year

**Relevant classes**:
CS 2110, CS 3110, CS 4410 & CS 4411, CS 2800, CS 3410, Probability (Math 4710).
Engineering math sequence- Multivariable Calculus, Linear Algebra, Differential Equations.
ECE 2220 Signal Analysis.
Lots of physics classes.
Current: CS 4780, CS 4320, CS 3220 (?), MATH 4220 Applied Complex Analysis

## Research

**When do you want to do research?**
I’m interested in starting this Fall, 2019.

**What is exciting to you about research?**
The last two summers, I interned at startups where I was using a lot of tools that other people made (API calls, etc), which is not very exciting to me - I would love to see other ways I could engage myself in the field. I think there is a lot of room for improvement in CS and would love to be a part of it - I’m excited about coming up with new ideas/tools and seeing them be used. Although I really enjoy theoretical work, I think implementation is crucial.

**What kind of research do you want to do?**

After I learned about OCaml and pattern matching and functional programming, I started thinking about how “powerful” certain languages are semantically and what tradeoffs there are between using/excluding certain language features. I'm interested in how we can benefit by taking advantage of certain features.

I’m definitely open to other fields besides programming language-specific research and want to explore more! I really enjoy math and physics too... 

## Optional Stuff

**Was there a paper that particularly excited you?**

**Is there a specific grad student or a project you're interested in working on?**
Dietrich’s work on Gator seemed interesting and I’d love to learn more about it!

**Anything else you want to tell us about yourself?**
I started making my own basic 3d renderer/simulation in Java from scratch, which is part of the cause for my excitement about Dietrich’s work- you can see that here: https://github.com/andrewpareles/3DTest.

**Attach a CV if you like.**
[Andrew_Pareles_Resume.pdf](https://github.com/cucapra/undergrad-research/files/3603528/Andrew_Pareles_Resume.pdf)

**Comment by Checkmate50** [comment]
Hey Andrew, thanks for reaching out!  I've sent you an email to schedule a research meeting.

**Comment by sampsyo** [comment]
Hi, Andrew! Are you still interested in research for the spring semester? We have a new project about implementing machine learning workloads on a novel, open-source, massively parallel processor. Let me know if you're interested and we can set up a meeting.

**Comment by andrewpareles** [comment]
Hi Adrian! That sounds really interesting--I'd love to meet about it. I am back in Ithaca the day classes start and free ~11-2 Tuesday and Thursday, 12-1 MWF. Do any of those times work?

**Comment by sampsyo** [comment]
Awesome! I'll send you an email about setting up a meeting.

**Comment by rachitnigam** [comment]
I assume @andrewpareles and @sampsyo met. @andrewpareles if you’re still looking for research positions, please reopen it!
