### ISSUE TITLE
Henry Liu

### ISSUE THREAD

**Issue by liuhenry4428** [cucapra/undergrad-research#23]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: Henry Liu

**Major**: Computer Science

**Year in Cornell**: 4th year

**Relevant classes**: 
- CS 3410 (TA'd for 2 semesters)
- CS 4410 (TA'd for 1 semester)
- CS 4420
- CS 4700 & 4701
- CS 4780
- CS 4820
- CS 4120 & 4121
- CS 6114 (enrolled)
- CS 6120 (enrolled)

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)

This semester, Fall 2019. I would like to pursue research for MEng credit.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)

I first started doing research junior year of high school at MIT through the PRIMES program. I initially applied because my high school didn't have much in terms of CS education and I wanted to explore different approaches to CS, and it turned out to be extremely rewarding because I was able to design, test, and evaluate a part of a project that I could call my own. I worked at MIT's Computer Science and Artificial Intelligence Laboratories (CSAIL) with Prof. Srini Devadas and a PhD student, and we worked to improve CPU cache scalability with a new cache coherence protocol. We then published our findings to [PACT 2016](https://dl.acm.org/citation.cfm?id=2967942). The next year, I worked with the same group on database logging algorithms, though I was unable to see that project to completion as I had to go off to college.

At Cornell, I've done some brief research with Prof. Knepper on Skynet Jr., which is a scaled-down self-driving car designed to do aggressive maneuvers such as sliding/drifting using sensor fusion algorithms and machine learning. However, the bulk of my research experience has been under Prof. Caunedo in the Economics department, where I'm currently working as a research assistant on a variety of tasks involving agricultural machinery prices and crop yields in developing countries. For example, one thing I did was geographically correlate used tractor price data that I scraped from several websites to crop yields (e.g. tons of bananas per acre) in the area with help of the Bing Maps API. The goal of this research is to see how the value depreciation in agricultural tools relate to agricultural output efficiency. 

I really like doing research because I like coming up with new solutions to a problem and then testing them to (hopefully) prove that they're successful. That's what I hope to get out of Capra.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")

I would prefer to do more empirical research instead of more theoretical work, but I'm definitely open to everything. 

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

I recently read[ The Design Philosophy of the DARPA Internet Protocols](http://ccr.sigcomm.org/archive/1995/jan95/ccr-9501-clark.pdf) by David Clark and really enjoyed it. It's not typical research paper that proposes something new, but it instead reflects back of the original design goals of the internet and discusses how they have shaped internet protocols and how well those goal are satisfied with the present state of the internet. It was really cool to learn about how and why the internet developed as it did.

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**
I really like compilers and computer architecture!

**Attach a CV if you like.**

**Comment by Checkmate50** [comment]
Hey Henry, thanks for reaching out!  I have a bit of an oddball project proposal for this semester.  

We've been working for the last year on the Gator language for reasoning about geometric operations, particularly in computer graphics.  We're looking to develop a game engine in Gator, both to demonstrate that we can develop a large-scale graphics project in the language and to figure out what new problems need to be tackled.

If this project sounds interesting, or if you want to hear more about Gator, let me know and I can forward you more information.

**Comment by liuhenry4428** [comment]
Hi @Checkmate50, this sounds really interesting and I'd love to learn more, both about Gator and what you think this project will entail.

**Comment by Checkmate50** [comment]
Thanks for your interest!

Gator introduces the notion of *geometric types*, which capture and manage geometric information about member objects.  These types allow our compiler to check that vector and scalar operations make geometric sense rather than just being numerically possible.  For instance, we can raise an error when a user attempts to add together two points in space; this operation is nonsensical but would normally be permitted through vector addition.

This project will involve using Typescript with Gator to build a graphics project (probably a 3D game of some sort) on the browser.  Our focus will be to explore how to use the geometric ideas of Gator to build complex shaders (graphics rendering programs), and how Gator could be extended into a real-world programming language.  Most of the work will be in building up the infrastructure for this project (we're building a game from scratch, after all!) and in learning how to represent existing shader ideas in Gator-style code.

If you would like to meet to discuss anything here further, shoot me an email at dag368@cornell.edu.  I can also send you a draft of the Gator paper, which explains the ideas and technical content of Gator in more detail.
