### ISSUE TITLE
Wan Qing Chua

### ISSUE THREAD

**Issue by wanqing0820** [cucapra/undergrad-research#25]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: Wan Qing Chua

**Major**: Computer Science (Intended) and Psychology

**Year in Cornell**: Freshman

**Relevant classes**:
INFO 1998 -602 Introduction to Machine Learning (Python)
INFO 1998 -603 Introduction to Backend Development (Python)
CS 1110 Introduction to Computing Using Python
PSYCH 2500 Statistics and Research Design (R for statistical analysis)

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I hope to be able to engage with higher level interests in computing beyond contents of classes. I hope to get involved during the semesters as well as the upcoming winter break.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
It is really inspiring listening to both professors and students alike, especially Professor Sampson talking about their ventures and experience in research. I am attracted by their excitement of discovery, problem solving and the grit in getting unstuck. It would be exciting to undertake a process of deeply engaging with the subject, and fundamentally mapping a mental network of knowledge in profound depth in the field. 

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I am looking to explore, and am excited about any learning opportunities.

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
Reconfiguring the Imaging Pipeline for Computer Vision

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**
I learnt fundamental knowledge of object oriented programming and data structures from online resources among other technical skills.

**Attach a CV if you like.**
[wc572_resume.pdf](https://github.com/cucapra/undergrad-research/files/3847878/wc572_resume.pdf)

**Comment by rachitnigam** [comment]
Hi @wanqing0820, if you’re still looking for research opportunities, can you email me at rnigam@cs.cornell.edu so we can setup a time to meet sometime next week?

**Comment by rachitnigam** [comment]
Scheduled a meeting with @wanqing0820 for 02/10.
