### ISSUE TITLE
Evan Adler

### ISSUE THREAD

**Issue by evanbenadler** [cucapra/undergrad-research#26]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: Evan Adler

**Major**: CS

**Year in Cornell**: Senior

**Relevant classes**:
3110 (completed)
formal verification, advanced programming languages, compilers (intended, at least, for next semester)

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
Spring 2020 semester

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I am doing an M.Eng. degree and would like to focus on PL. Doing the kind of research Capra does is interesting because it is hands on programming languages work.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
Just something involving PL

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**

**Comment by sampsyo** [comment]
Hi, Andrew! Thanks for getting in touch, and thanks also for your patience. While it's only kinda PL-adjacent, we have a new project about implementing machine learning workloads on a novel, open-source, massively parallel processor. Let me know if you're interested and we can set up a meeting.

**Comment by Checkmate50** [comment]
Hey Evan!  As another option, since you mentioned you're interested in the PL side of things, I'm currently looking for someone to work on a compiler for Gator, a language built around geometry types for graphics.  If that sounds interesting, let me know and we can schedule a meeting.

**Comment by evanbenadler** [comment]
Hi Professor Sampson,

Sorry I didn't get back to you sooner. This project seems extremely
exciting and I'd be interested in learning more about it. Please let me
know if you still have time to schedule a meeting.

Thanks,

Evan Adler

**Comment by Checkmate50** [comment]
Hey Evan, sounds good -- if you could send me an email at dag368@cornell.edu, I'll send you some more detail about the Gator project and we can schedule a meeting

**Comment by sampsyo** [comment]
Yo—I'll let you talk to @Checkmate50 first! I think we might have enough person-power for the other project, but I'll get back to you in case we still need somebody (and you're still looking).
