### ISSUE TITLE
Michelle Chao

### ISSUE THREAD

**Issue by mchao409** [cucapra/undergrad-research#27]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: Michelle Chao

**Major**: Computer Science

**Year in Cornell**: Sophomore

**Relevant classes**: CS 2112, CS 2800, CS 3110, CS 3410, CS 4820, CS 4780
Currently enrolled in CS 4110/11, CS 4670, CS 4786

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
During the school year, hopefully starting SP20

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I’d like to use research as an opportunity to apply some of the foundational knowledge I’ve learned at Cornell to something larger outside of class, hopefully pulling from different areas of CS/ECE that I've encountered so far.
Although I haven’t thought about continuing on to grad school, I’d also like to see if it’s something I’d want to pursue.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
A few of the areas I’m interested in exploring are applied machine learning, as well as the relationship between software and hardware in efficiency. I am not very familiar with PL, but am open to learning more about the area. I enjoy solving programming problems and I’d be interested in working with algorithms/software optimization as well. 

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
A paper that I enjoyed reading was about the development of Google's file system and it's design and architecture. After reading a bit about the system, I worked on building a simple distributed file system that incorporated a few of the concepts (recoverability/fault tolerance) that the paper discussed.
https://static.googleusercontent.com/media/research.google.com/en//archive/gfs-sosp2003.pdf
**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**

**Comment by sampsyo** [comment]
Hi, Michelle—great to meet you! Sounds like you might be a good fit for several projects, but one we're interested in getting started on soon is about implementing machine learning workloads on a novel, open-source, massively parallel processor. Let me know if you're interested and we can set up a meeting.

**Comment by mchao409** [comment]
Hi Professor Sampson,

Thank you for getting back to me! I'd definitely be interested in learning more about the project -- when would be a good time for a meeting this week?

**Comment by sampsyo** [comment]
Cool! Can you send me an email at asampson@cs.cornell.edu and we'll find a time to meet? (I'm traveling this week, though, so it will need to be next week.)

**Comment by rachitnigam** [comment]
I assume @mchao409 met with @sampsyo. I’m going to close the issue. @mchao409 if you’re still looking for positions, please reopen it!
