### ISSUE TITLE
Paul Joo

### ISSUE THREAD

**Issue by pauljoo28** [cucapra/undergrad-research#29]
## Personal Details

**Paul Joo**:

**Computer Science**:

**Junior**:

**CS 3110, CS 4160 (Possibly this semester still thinking about it...)**:

## Research

**When do you want to do research?**
I want to do research this semester and possibly extend to senior year.

**What is exciting to you about research?**
I originally was in AEP but switched over the computer science because I found more interest in it after taking more computer science courses. Before I was doing research on computational chemistry and I thought that the most exciting thing about research internally was the problem solving aspect of it. I also get external satisfaction when I think about how I am working with a community of people all building upon each others work to get to the same goal.

**What kind of research do you want to do?**
I am looking to explore! I really enjoyed CS 3110 and am very curious about the application of programming languages. It seems like a science that is very fundamental and could alter the way you could look at problems.

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

**Is there a specific grad student or a project you're interested in working on?**
Programming Abstractions for Natural Language & Intelligent Systems looks really interesting but I am open to anything. I am generally attracted to this theme that you could simplify complex problems through programming languages.

**Anything else you want to tell us about yourself?**
I like cooking and watching basketball?

**Attach a CV if you like.**
[Resume_Software_Engineering.pdf](https://github.com/cucapra/undergrad-research/files/4106577/Resume_Software_Engineering.pdf)

**Comment by Checkmate50** [comment]
Hey Paul, thanks for reaching out!  If you're still interested in a project, I'm looking for help with projects on the Gator language and compiler -- Gator is a language for reasoning about geometry with types.  Send me an email at dag368@cornell.edu if interested, and I can follow up with more information.
