### ISSUE TITLE
Benjamin Posnick

### ISSUE THREAD

**Issue by benjaminmposnick** [cucapra/undergrad-research#3]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here is [an example](https://github.com/cucapra/undergrad-research/issues/1) of a filled out template for reference.

## Personal Details

**Name**: Benjamin Posnick

**Major**: Computer Science

**Year in Cornell**: Sophomore

**Relevant classes**: CS 3410 (Computer Systems Organization and Programming), CS 4700+4701 (Foundations in Artificial Intelligence + Practicum),  CS 2110 (Object-Oriented Programming and Data Structures), CS 2800 (Discrete Structures)

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I would like to get involved in research during the semester, potentially getting a head start by beginning before this current spring semester ends so that I can hit the ground running in the fall.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I have previous research experience in computational biology and scientific computing at Syracuse University. This REU program inspired me to continue doing research during my time at Cornell. I enjoy the excitement of doing things others haven't done before -- bridging the gap between what is known/possible now and the unknown.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
Research that involves computer architecture as well as software/PL. A good blend of these elements is my ideal scenario.

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
The information on your website regarding this project really intrigued me!
https://capra.cs.cornell.edu/research/eva2/

**Is there a specific grad student or a project you're interested in working on?**
Not sure yet, but there are several projects that sound very exciting to me!

**Anything else you want to tell us about yourself?**
I actually have a my name as second author on a publication already from research I did during the summer before my senior year of high school in materials/polymer science, back before I switched my major and focus from chemical engineering to computer science.

**Attach a CV if you like.**
[Resume.pdf](https://github.com/cucapra/undergrad-research/files/3060617/Resume.pdf)

**Comment by sampsyo** [comment]
Hi, Benjamin! You mentioned over email to me that you are interested in learning more about [Seashell](https://github.com/cucapra/seashell). It's hard to predict exactly where that project will be in the fall, but let's keep in touch. In the mean time, why don't you try setting up the compiler and poking around in the documentation for the language? We have some docs, lots of tests, and some examples to try out. Please let us know how your exploration goes and if you have any questions along the way.

**Comment by benjaminmposnick** [comment]
Hi again Prof. Sampson:

That sounds like a good plan to me. I’ll try to take a look at the compiler over the summer to get accustomed to it and I can drop you a line with questions over the summer and touch base again towards the fall semester.

Have a great summer!

Benjamin Posnick
B.S. Computer Science ‘21
Cornell University // College of Engineering
Cell // 315.877.7131

**Comment by rachitnigam** [comment]
Since the thread has gone stale, I’m going to close it. @benjaminmposnick if you’re still looking for research opportunities, feel free to reopen it.
