### ISSUE TITLE
YooNa Chang 

### ISSUE THREAD

**Issue by aness0528** [cucapra/undergrad-research#30]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

## Personal Details

**Name**: YooNa Chang 

**Major**: Computer Science 

**Year in Cornell**: Sophomore

**Relevant classes**: CS3110, CS2110, CS2800, CS3410 (currently taking this semester)

## Research

**When do you want to do research?**
I want to start with research in Spring2020.

**What is exciting to you about research?**
I have mostly learned the programming side of computer science until now. The things I learned increasingly led me to get interested in computer architecture, specifically how the computer itself relates to the tools we use to program and how a programmer successfully interacts with the computer to bring about the results he or she wants. 

**What kind of research do you want to do?**
I don't know and I'm looking to explore! 

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[Resume_YooNa_Chang (3).pdf](https://github.com/cucapra/undergrad-research/files/4118549/Resume_YooNa_Chang.3.pdf)

**Comment by rachitnigam** [comment]
Hi @aness0528! Thanks for reaching out! If you’re still looking for research opportunities, please email me at rnigam@cs.cornell.edu so we can setup time to meet and chat next week.

**Comment by rachitnigam** [comment]
Scheduled a meeting with @aness0528 for 02/10.
