### ISSUE TITLE
Patrick LaFontaine

### ISSUE THREAD

**Issue by Pat-Lafon** [cucapra/undergrad-research#32]
## Personal Details

**Name**: Patrick LaFontaine

**Major**: Computer Science

**Year in Cornell**: Junior (3rd year)

**Relevant classes**: (Assume relevant prereqs)4410/1, 4120/1(SP20), 4810, 4999(Myers, FA19 and SP20)

**Interested in continuing research during the summer:** Yes, see below

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I am looking for a research opportunity for the summer.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I am currently working with Matthew Milano on the Gallifrey language and have had(/am having) an absolute blast(Joined via cs research night). With him graduating and most of the people I have worked with over the two semesters leaving, I am looking to join a new project. I'm still finding new areas of interest that excite me but I've found myself spending a lot of time learning about how programming languages are implemented and how they can be designed/implemented to make programming easier and faster(a little vague/general with this). Research, to me, is a way to really dive into these kinds of questions to understand how things work and more importantly, find new/better ways that they can be done.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I'm still very open in my interests and to new fields but I'm generally looking to work in and around the compiler along with the design of the language that it takes in and the code that it generates(again kind of vague). I've (so far) really enjoyed compilers and it's a class I've looked forward to taking since I took 3110 so I would like to use research as an opportunity to build on that class if possible. I've been exposed to/worked with the more theory side of type systems from my research and personal interest but I think I prefer to work closer to code.

## Background

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
The work of "MemorySanitizer: fast detector of uninitialized memory use in C++" and "RustBelt: Securing the Foundations of the Rust Programming Language" have probably been the most influential on how I think about language designs/problems and how programmers interact with them. Very recently I stumbled upon the talk for "On the Impact of Programming Languages on Code Quality" which along with the paper have been rather thought provoking(especially with having to choose a language for compilers). 

**Is there a specific grad student or a project you're interested in working on?**
I've briefly corresponded with Dietrich Geisler about the Gator project to learn more about it. My main interests there(influenced by his suggestions) are with Gator's interlope with C/C++, support for dimension analysis of types, and expression optimization. I am open to other projects that are available, with HBIR being another public project that looked very interesting.

**Anything else you want to tell us about yourself?**
There's probably an 80% chance I apply to grad school for phd programs.

**Attach a CV if you like.**

**Comment by rachitnigam** [comment]
Hey @Pat-Lafon, I work on Dahlia (https://github.com/cucapra/dahlia) which is a programming language that uses affine type systems to program FPGAs. If you're interested in chatting, shoot me an email at rnigam@cs.cornell.edu
