### ISSUE TITLE
Ziyao Cheng

### ISSUE THREAD

**Issue by KellyCzy** [cucapra/undergrad-research#33]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Ziyao Cheng

**Major**: Computer Science

**Year in Cornell**: Sophomore

**Relevant classes**: CS 4670 Computer Vision,  CS 4780 Machine Learning,  CS 3420 Embedded Systems, ECE 2300 Digital Logic and Computer Organization, CS 3110 Functional Programming, CS 4820 Introduction to Algorithms, CS 2300 Intermediate Web Design.

**Interested in continuing research during the summer:** Yes

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I would like to start this semester and keep on doing over the summer and in the future as well.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I'm excited by how hardware can facilitate software development or computation. I'm especially interested in high-level implementation of computer vision method using facilitated hardware.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I'm most interested in research that involves Machine Learning or Computer Vision technique or algorithm development or research about computer hardware that facilitate computations.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[Resume.pdf](https://github.com/cucapra/undergrad-research/files/4259162/Resume.final.copy.pdf)

**Comment by rachitnigam** [comment]
@KellyCzy if you're still looking for a position, can you open an issue with the new template? Also, FWIW, I don't know if anyone in our group is working on machine learning directly. @tissue3 probably has the most relevant projects so tag her if you open the issue.
