### ISSUE TITLE
Natalie Isak

### ISSUE THREAD

**Issue by natalieisak** [cucapra/undergrad-research#34]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Natalie Isak

**Major**: Computer Science

**Year in Cornell**: Sophomore 

**Relevant classes**: CS 1110 (consultant), CS 2110, ECE 2300, CS 2800, CS 3110 (curr.), CS 3300 (curr.), CS 4670 (curr.)
Special Interest: Ling 1011, CS 2850 

**Interested in continuing research during the summer:** I unfortunately have already accepted an internship. However, I would be interested in continuing this research next year.

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.) 
As soon as possible! 

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
Most of all, I hope to gain exposure to different fields in computer science through research. At this stage in my life, I am looking to gain experience in as many fields as possible, and I believe that doing research is an ideal method of doing so. Second, I currently do research for AguaClara. 
[Natalie Isak Resume 12_22_19_v2.pdf](https://github.com/cucapra/undergrad-research/files/4259358/Natalie.Isak.Resume.12_22_19_v2.pdf)
[Natalie Isak Resume 12_22_19_v2.pdf](https://github.com/cucapra/undergrad-research/files/4259360/Natalie.Isak.Resume.12_22_19_v2.pdf)

I have loved this experience so far and I would love to continue this fulfilling experience.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I would be most interested in doing research in natural language processing. I am currently taking a linguistics class, and I would love to learn more about the intersection of the two. 

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
I found reading about Opal to be extremely interesting. I enjoyed learning more about the current shortfalls of machine learning and how the features within Opal are aiding these issues. 

**Is there a specific grad student or a project you're interested in working on?**
I'd be interested in anything related to programming languages or natural language processing. 

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[Natalie Isak Resume 12_22_19_v2.pdf](https://github.com/cucapra/undergrad-research/files/4259361/Natalie.Isak.Resume.12_22_19_v2.pdf)

**Comment by rachitnigam** [comment]
Hi Natalie! Hope your internship went well. If you're still looking for research, please reopen this issue.
