### ISSUE TITLE
Vivian Dai

### ISSUE THREAD

**Issue by viviandai** [cucapra/undergrad-research#35]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Vivian Dai

**Major**: Undeclared (Computer Science and ORIE)

**Year in Cornell**: 1st year

**Relevant classes**: CS 1110, CS 2110, ENGRI 1101

**Interested in continuing research during the summer:** Yes

## Research

**When do you want to do research?**
I'd like to get involved starting this summer, whether it be at Cornell or from home. I'd also be interested in continuing into the next school year as well, if that is possible.

**What is exciting to you about research?**
I love the idea of solving new problems that I would be truly passionate about, instead of just using computer science in industry. I think that having a deeper connection to what I am working on is exciting, and I would love to find something in computer science that sparks that level of interest and passion for me that I can dedicate myself to.

**What kind of research do you want to do?**
I haven't had the opportunity to become very familiar with different specific fields in computer science yet, so I'm glad to explore what there is!

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

**Is there a specific grad student or a project you're interested in working on?**
I am open to anything!

**Anything else you want to tell us about yourself?**
While I don't have the most experience as a first-year student, I am an eager learner, and I would be grateful for the opportunity to take on any readings or coursework needed to make myself a valuable researcher!

**Attach a CV if you like.**
[resume.pdf](https://github.com/cucapra/undergrad-research/files/4384116/resume.pdf)

**Comment by rachitnigam** [comment]
Hi @viviandai, thanks for reaching out! I work on programming language design for custom hardware. If you’re interested, please take a look at [Dahlia](https://Capra.cs.cornell.edu/dahlia), a language we’ve been working on and the associated research paper: https://rachitnigam.com/files/pubs/dahlia.pdf

If any of this sounds interesting, we should setup a video chat!

**Comment by viviandai** [comment]
Hi! I've taken a look at the research paper and your work. I'm a bit worried that I wouldn't have the most to contribute, since I don't have as much experience (especially with hardware) and am a bit more interested in less hardware-related research. Would this be plausible with Dahlia, or would there be other projects?

**Comment by rachitnigam** [comment]
Hey Vivian,

You don’t have to worry about not knowing enough to contribute. The point of undergrad research is to learn new things and try to solve problems! Everyone has to start learning somewhere and with research, we’re all learning all the time.

Regarding less hardware: while the paper might give you the impression that most of what we do is hardware related, we’re *actually* interested in language design. Hardware is just a domain we apply our research to. Depending on your interests, you can do anything from designing and proving language properties to real hardware hacking.

**Comment by viviandai** [comment]
Hi,

Thanks for the reply! That makes a lot of sense, and it does help with my
considerations. I would love to learn more and have a video chat if that is
still possible.

Best,
Vivian

**Comment by rachitnigam** [comment]
Great! Send me a list of your available times at rnigam@cs.cornell.edu and I’ll schedule something.
