### ISSUE TITLE
Barry Wang

### ISSUE THREAD

**Issue by GithuBarry** [cucapra/undergrad-research#36]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Barry Wang

**Major**: Information Science, Systems and Technology _(subject to change)_

**Year in Cornell**: 2nd

**Relevant classes**: [CS2112](https://www.cs.cornell.edu/courses/cs2112/2019fa/), [CS2800](https://courses.cs.cornell.edu/cs2800/wiki/index.php/CS_2800_Fall_2019). In progress: [CS3110](https://www.cs.cornell.edu/courses/cs3110/2020sp/), [CS3152](https://www.cs.cornell.edu/courses/cs3152/2020sp/), [CS4670](https://www.cs.cornell.edu/courses/cs4670/2020sp/)

**Interested in continuing research during the summer:** Yes

## Research

**When do you want to do research?**
I wish to start on research in Summer 2020.

**What is exciting to you about research?**
Research shapes our knowledge, and contributions to it is tremendously meaningful.
To me personally, research looks like a shortcut from my textbook to some knowledge boundaries. With a sense of a mission, research is a perfect source of motivation for me to learn things quickly to fill gaps in order to contribute while breaking any hesitation of mine. 

**What kind of research do you want to do?**
I am exploring and can easily become excited about virtually anything in Capra. 

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(I skimmed some papers in Capra and I observed that I was excited by papers that I could better understand. Hence I conclude that I do not have a strong focus right now.)

**Is there a specific grad student or a project you're interested in working on?**
I might be more helpful in Computer Vision related researches because I am taking the course this semester (Spring 2020).

**Anything else you want to tell us about yourself?**
I recently return to China due to the COVID-19 pandemic. I might have to work on things remotely (and if so I am available most Eastern time mornings and noons in summer) depending on the outbreak situation (and the U.S. border control).

**Attach a CV if you like.**
[Barry's Resume](https://drive.google.com/open?id=1LTjNRGywFukkGGUPsDoW5nfW4XJDF95H)

**Comment by rachitnigam** [comment]
Hi Barry! If you're still looking for a research position, please open a new issue with the updated template. Since you're presumably a third year now, we require you to answer a few more questions.
