### ISSUE TITLE
Vaishnavi Gupta

### ISSUE THREAD

**Issue by vaishnavi17** [cucapra/undergrad-research#37]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Vaishnavi Gupta

**Major**: Computer Science

**Year in Cornell**: Freshman

**Relevant classes**: CS 1620, CS 2112, CS 2802, CS 3110

**Interested in continuing research during the summer:** Yes, either remotely or in Ithaca.

## Research

**When do you want to do research?**
I'd want to start research over the summer, and hopefully continue it over the semester as well.

**What is exciting to you about research?**
I first decided to major in CS after working on a project regarding public health, where I first got to apply my CS knowledge to a real-life problem. I feel like that's one of the most exciting things about learning something new, and research is the perfect way to dive deeper into topics that interest me in class. I've previously explored research in bioinformatics, but I'm hoping to explore a different field in CS and figure out what I'd be interested in for grad school.

**What kind of research do you want to do?**
At this point, I'm open to any kind of project, but ideally something more application oriented because I feel like that's where I'd be able to contribute the most. While taking 3110, I became interested in the process of creating and implementing new languages, so that seems like a cool aspect of Capra! I'm also interested in projects that incorporate graphics and computer vision.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**

**Is there a specific grad student or a project you're interested in working on?**
I briefly talked to Dietrich Geisler about his Gator project a while back, but I'd be open to any project!

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[Gupta_Vaishnavi.pdf](https://github.com/cucapra/undergrad-research/files/4617844/Gupta_Vaishnavi.pdf)

**Comment by rachitnigam** [comment]
Hi Vaishnavi! If you're still looking for a research position, can you reopen the issue? You can tag Dietrich (@Checkmate50) if you're still interested in working with him.

**Comment by vaishnavi17** [comment]
Hi, yes, I'm still interested in a research position! I would be interested in working with Dietrich (@Checkmate50) or anyone else with open spots.

**Comment by Checkmate50** [comment]
Hey Vaishnavi!  Thanks for following up; I was busy this Summer with an internship and wasn't sure if you were still interested in research for Fall.  If you could send me an email at dag368@cornell.edu, we can setup a meeting time to discuss a potential project.

**Comment by rachitnigam** [comment]
Cool! @vaishnavi17 feel free to ping this thread if you want me to reopen this after the chat. No need to do anything if you decide to work with Dietrich!
