### ISSUE TITLE
Daniel McNeary

### ISSUE THREAD

**Issue by danmcneary** [cucapra/undergrad-research#38]
## Personal Details

**Name**:
Daniel McNeary

**Major**:
Computer Science

**Year in Cornell**:
Sophomore (Rising Junior)

**Relevant classes**: 
CS 3410, CS 3110, CS 2110, CS 1110,
CS 4160, CS 2802

**Interested in continuing research during the summer:** Yes

## Research

**When do you want to do research?**
As of right now I could do research whenever possible.

**What is exciting to you about research?**
I've had an interest in the foundational scientific and experimental methods behind computer science ever since I took a basic Java programming class during 9th grade. In particular I was interested in the idea of discovering new frontiers in computer science that could lead to better and more pleasant experiences for the end user. It's interesting how the formulation of new abstract constructs can allow people to perform tasks that just before seemed practically infeasible. On top of that I also think it's satisfying to understand such constructs. So although I lack experience in research, I'd like to learn a little more about the process for progressing towards these discoveries. After taking CS 3410 with Weatherspoon and learning about the misconceptions I had about the study of "hardware" concepts, I'm also interested in learning more about the operation of lower level systems and computer architecture. 

**What kind of research do you want to do?**
I'm interested in doing work involving computer architecture and systems. I also appreciate programming language theory and design. The usage of tools such as inductive evaluation relations and type systems to facilitate predictable, classifiable code is of rather strong interest to me, based on past classes. Needless to say I'd also be interested in other kinds of research, including research in areas I've had less exposure to.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
The paper on Dahlia interested me. When I was taking CS 3410 I started to become more interested in the interaction between lower level hardware and high level programming constructs. When I tried to add memory mapped I/O extensions and a program to my RISCV general purpose CPU in order to allow it to run Pong, I was disappointed by the low clock speed. I started to think about what it might entail in order to efficiently distribute tasks away from the CPU in order to allow the game to run at a higher speed. I decided that I didn't have any idea how to add hardware accelerators for that particular program. So to me Dahlia seems interesting as a way to generate hardware accelerators for FPGAs using more understandable high level constructs in a way that guarantees reasonably simple designs and enforces predictable programming patterns. As a person who is looking to learn more about computer architecture, it's also interesting how Dahlia syntax and type checking constructs reflect whats actually going on in the underlying hardware designs in terms of loop unrolling and memory banking.

**Is there a specific grad student or a project you're interested in working on?**
I'd be interested in doing work related to Dahlia, I'm sure I could make any other project work as well.

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[myresume.pdf](https://github.com/cucapra/undergrad-research/files/4733836/myresume.pdf)

**Comment by rachitnigam** [comment]
Hi Daniel! Thanks for reaching out! Unfortunately for the summer, the Dahlia project is at max capacity. We can either 1) wait till next semester to start research on Dahlia, or 2) if one of the other projects have room, the other grad students might respond. 2) might be unlikely because were well into summer research by now. If you’re interested in 1), either @ me on this thread or send me an email at rnigam@cs.cornell.edu towards the end of summer.

**Comment by rachitnigam** [comment]
Hey Daniel! If you're still looking for a research position, please reopen this issue.

**Comment by danmcneary** [comment]
@rachitnigam Hi, I'm still interested in research.
