### ISSUE TITLE
Yaoyao Ma

### ISSUE THREAD

**Issue by YaoyaoM** [cucapra/undergrad-research#4]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here is [an example](https://github.com/cucapra/undergrad-research/issues/1) of a filled out template for reference.

## Personal Details

**Name**: Yaoyao Ma

**Major**: Computer Science

**Year in Cornell**: 1st year

**Relevant classes**: CS 1110, CS 2110, CS 2800, CS 1998, CS 4998, MATH 2210

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I want to do research over summer 2019 and potentially continue into the fall semester.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I first got interested in research in high school when I was a research intern in the Institute of Oceanology at Chinese Academy of Sciences. It was a really rewarding experience seeing the work that I've done can contribute a little to the bigger overall project for the researchers. It is also amazing when I got to actually understand a few pages of the researcher's paper with guidance and individual learning. I am really interested in the formation of programming languages and the way they are processed in different systems and would love to learn more about the interaction between softwares and harwares. It is exciting for me to learn new things in a different perspectives and have a deeper understanking of the projects or technology that people who are top at their field are working on.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I'm willing to learn and explore!

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
https://ecommons.cornell.edu/handle/1813/5958 The paper on an algorithm for determining if two finite automata with start states are equivalent is exciting since it is closely related to what I just learn about automata in the course CS 2800. To approach the problem in a linear way seems to be in a rigorous logic and clear to follow in real-life applications on machines.

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
Resume: https://drive.google.com/file/d/1NnFe9IYS26-aIDlpVbk4U6TQEHdW4OOM/view?usp=sharing
LinkedIn: https://www.linkedin.com/in/yaoyaoma/

**Comment by sampsyo** [comment]
Hi! If you’re still looking for something to do over the summer, we have something pretty specific we could use help with.

We’re working on this [programming language for custom hardware accelerator design](https://github.com/cucapra/seashell). It uses a fancy type system to provide guarantees about how the hardware implementation corresponds to an algorithmic specification. The compiler is working and we’re making progress on implementing a suite of benchmarks, and we could use help with one of two things:

1. **Porting to [AWS F1][f1].** Our toolchain currently runs on a single FPGA we have in the lab, but we would love to be able to run on a larger FPGA in the cloud—and to let other people use the language just by spinning up a VM. Your task would be to learn about how AWS and F1 works, bring up our current toolchain there, write lots of supporting tooling to make this all work, and thoroughly document the process so anyone can get started using our language. This would be good for anyone but especially good if you’re interested in cloud computing.
2. **An [Intel HLS][ihls] backend.** Our compiler currently targets the [Xilinx][] ecosystem, but it should also hypothetically work just as well for Intel FPGAs. We want to build a new backend for our compiler that emits the OpenCL code that the Intel toolchain takes as an input. This task would be especially good if you are interested in learning about compiler hacking. Our compiler is implemented in Scala, so it would also be an opportunity to learn that language.

Do either of those appeal? Let us know and we’ll talk more!

[f1]: https://aws.amazon.com/ec2/instance-types/f1/
[xilinx]: https://www.xilinx.com
[ihls]: https://www.intel.com/content/www/us/en/software/programmable/quartus-prime/hls-compiler.html

**Comment by YaoyaoM** [comment]
Hi Professor Sampson,
Thanks so much for your reply! I have just confirmed to do a summer software engineering internship in Ithaca for a startup that I will be matched with by the Life Changing Labs Summer Incubator Program that is sponsored by Cornell Entrepreneurship. It will be full-time from 6.10 to 8.2. But it will still be nice to talk to you if you are available to see if there are any opportunities to work with you part-time or maybe next semester since I am still interested in the topics that you are working on. I am available next week with these dates and time:
Monday, May 6th: 12:00-18:00;Tuesday, May 7th: All day;Wednesday, May 8th: All day;Friday, May 10th: 10:00-14:30; 17:00-19:30.
Thanks so much for your time and consideration!
Best,Yaoyao Maym284@cornell.edu


    On Friday, May 3, 2019, 8:42:21 AM EDT, Adrian Sampson <notifications@github.com> wrote:  
 
 
Hi! If you’re still looking for something to do over the summer, we have something pretty specific we could use help with.

We’re working on this programming language for custom hardware accelerator design. It uses a fancy type system to provide guarantees about how the hardware implementation corresponds to an algorithmic specification. The compiler is working and we’re making progress on implementing a suite of benchmarks, and we could use help with one of two things:
   
   - Porting to AWS F1. Our toolchain currently runs on a single FPGA we have in the lab, but we would love to be able to run on a larger FPGA in the cloud—and to let other people use the language just by spinning up a VM. Your task would be to learn about how AWS and F1 works, bring up our current toolchain there, write lots of supporting tooling to make this all work, and thoroughly document the process so anyone can get started using our language. This would be good for anyone but especially good if you’re interested in cloud computing.
   - An Intel HLS backend. Our compiler currently targets the Xilinx ecosystem, but it should also hypothetically work just as well for Intel FPGAs. We want to build a new backend for our compiler that emits the OpenCL code that the Intel toolchain takes as an input. This task would be especially good if you are interested in learning about compiler hacking. Our compiler is implemented in Scala, so it would also be an opportunity to learn that language.

Do either of those appeal? Let us know and we’ll talk more!

**Comment by sampsyo** [comment]
Aha, great! That sounds like a really cool program. I think you should focus on your internship this summer and not worry about trying to also balance research. But let's keep in touch and see how things look in the fall!

**Comment by YaoyaoM** [comment]
Got it. Thanks so much!



On Saturday, May 4, 2019, 15:32, Adrian Sampson <notifications@github.com> wrote:


Aha, great! That sounds like a really cool program. I think you should focus on your internship this summer and not worry about trying to also balance research. But let's keep in touch and see how things look in the fall!

**Comment by rachitnigam** [comment]
Since the thread is stale, I’m going to close it. @YaoyaoM if you’re still looking for research opportunities, feel free to reopen it. If not, good luck with everything!
