### ISSUE TITLE
Saksham Mohan

### ISSUE THREAD

**Issue by Saksham-Mohan** [cucapra/undergrad-research#42]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Saksham Mohan

**Major**: Computer Science and Economics

**Year in Cornell**: Senior

**Relevant classes**: CS 3110, CS 3410, CS 4820, ORIE 4741, CS 4670 

**Interested in continuing research during the summer:** Yes, definitely!

## Research

**When do you want to do research?** 
This Semester (Fall 2020)

**What is exciting to you about research?**
Right from when I took CS 2800 and studied Automata theory, I have always enjoyed the theoretical portions of my Computer Science courses a lot. While I have had plenty of experience in practical application of computer science concepts, I feel that my time here as an undergraduate has lacked an experience that allows me to contribute to the growth of knowledge in a field of interest. What really spiked my interest and prompted to pursue research this semester was studying the Programming Languages module in CS 3110 and implementing my own interpreter in one of the assignments. 

**What kind of research do you want to do?**
As mentioned in the previous answer, I would love to get involved in a PL oriented project! In addition, I have past experience with Machine Learning and Computer Vision so would be willing to work on projects related to those too. 

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
I really enjoyed reading a paper titled "Java and Scala's Type Systems are Unsound" by Ross Tate and Nada Admin. I stumbled upon the paper while browsing the PL@Cornell website. 

**Is there a specific grad student or a project you're interested in working on?** 
I was pretty intrigued by the "Programming Abstractions for Natural Language & Intelligent Systems" project on the CAPRA website. I also enjoyed reading about Dahlia and Braid programming languages. While these 3 project struck out to me, I am pretty flexible and willing to work on any other projects that might be a better fit. 

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[Final Resume.pdf](https://github.com/cucapra/undergrad-research/files/5174561/Final.Resume.pdf)

**Comment by Checkmate50** [comment]
Hey Saksham!  I'm Dietrich, a grad student working with Adrian on research related to programming languages for computer graphics ala Braid.  If you're interested, shoot me an email at dag368@cornell.edu and we can talk about a potential research project.

**Comment by rachitnigam** [comment]
@Checkmate50 if the meeting went successfully, can you close the issue? If not, can you comment saying so?

**Comment by Checkmate50** [comment]
We had a good meeting, but I got overwhelmed this semester and couldn't take on more researchers
