### ISSUE TITLE
Aparajito Saha

### ISSUE THREAD

**Issue by AparajitoSaha** [cucapra/undergrad-research#44]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Aparajito Saha

**Major**: Electrical and Computer Engineering, Computer Science

**Year in Cornell**: 3rd Year

**Relevant classes**: CS 4410, ECE 4750, ECE 3140, CS 3110

**Interested in continuing research during the summer:** Yes

## Research

**When do you want to do research?**
I'd like to begin in Spring 2021 and continue through the summer into the following academic year.

**What is exciting to you about research?**
I enjoy exploring unique ideas and projects, and the notion of being at the forefront of development is extremely exciting! I'm really interested in the intersection of the software and hardware domains in computing, especially in helping people access technology to accelerate conventional programs. 

**What kind of research do you want to do?**
I'm not sure, I do want to explore further! I'm interested in making ML more streamlined in large applications and maximize hardware performance for such problems. I'm also fascinated in making hardware accelerators more convenient to use via simulation.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
I read about the Stripe intermediate representation as given in "Stripe: Tensor Compilation via the Nested Polyhedral Model" (Zerrell, Bruestle). I was particularly fascinated by the use of the intermediate representation to manage not only the type of accelerator on which code for an ML task was being run, but also the memory "parallelization" enabled by the polyhedral nesting that the paper develops. I am also very curious on how the compiler for Stripe is able to concretely separate out the algorithm for the ML task away from the hardware configurations, especially when considering multiple parallel hardware accelerators.

**Is there a specific grad student or a project you're interested in working on?** 
I got to learn about the Gator project from Dietrich at the ACSU Research Night - I thought that was really cool and would love to work on that, though I'm open for anything! 

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[AparajitoSaha_Resume.pdf](https://github.com/cucapra/undergrad-research/files/5197903/AparajitoSaha_Resume.pdf)

**Comment by rachitnigam** [comment]
Hi @AparajitoSaha, if you're still interested in doing research this semester (Fall 2021), please reach out to me at rnigam@cs.cornell.edu so that we can setup a time.
