### ISSUE TITLE
Joshua Kaplan

### ISSUE THREAD

**Issue by jgkaplan** [cucapra/undergrad-research#45]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Joshua Kaplan

**Major**: Computer Science / Math

**Year in Cornell**: Senior

**Relevant classes**: Honors Object Oriented Programming and Data Structures, Data Structures and
Functional Programming, Discrete Math, Systems Programming, Programming Languages and Logics, Introduction to Analysis of Algorithms, Introduction to Game Design, Applied Logic, Machine Learning for Intelligent Systems, Introduction to Theory of Computing, Competition Programming and Problem Solving Seminar, Category Theory, Operating Systems, Compilers, Programming Languages Seminar

**Interested in continuing research during the summer:** Yes

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
During this and next semester.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I really enjoy thinking about and solving puzzles in various forms. I see figuring out how to create user friendly, powerful, elegant languages and type systems as an extension of that. I like trying out new ideas and finding better ways to do things that are annoying in other languages. I'm thinking of going to grad school, and I want to figure out if I enjoy doing research before that.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I'm not entirely sure. I like type systems, linear logic, and interesting languages. In the future, I want to work on developing a user-friendly high level quantum computing language.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
There was a paper recently presented at PLDI 2020. "Silq: A High-Level Quantum Language with Safe Uncomputation and Intuitive Semantics." This paper (and corresponding presentation) excited me because it's closely related to what I want to work on in the future.

**Is there a specific grad student or a project you're interested in working on?**
Not sure.

**Anything else you want to tell us about yourself?**
I'm a member of PLDG, currently TAing for 4110.

**Attach a CV if you like.**
[Resum_.pdf](https://github.com/cucapra/undergrad-research/files/5216581/Resum_.pdf)

**Comment by Checkmate50** [comment]
I heard that you got another research position.  If this is incorrect or if you are still interested in a position with us, could you reopen this issue?
