### ISSUE TITLE
Chris Gyurgyik

### ISSUE THREAD

**Issue by cgyurgyik** [cucapra/undergrad-research#46]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Chris Gyurgyik

**Major**: Computer science

**Year in Cornell**: Senior

**Relevant classes**:  2800, 3110, 3410, 4410

**Interested in continuing research during the summer:** I would be interested in continued research over the summer.

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I would like to do 3-credit hours a week, if possible.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I've never been part of a formal research team. However, I love problem solving and I love working on real world projects. Last semester, myself and a few others took on a problem in computer graphics of how to render spherical volumes without using the classic cartesian coordinate system. It was difficult, yet very rewarding at the same time. Over the summer, I've taken a small part in LLVM, and found the community to be a good one to work with.

**What kind of research do you want to do?**
I've really enjoyed working with the LLVM org. I like optimization, and I am eager to learn more about compilers and intermediate representation of languages. If at all relevant, I've taken a huge interest in the evolution of C++, as well as programming languages in general.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
I don't recall a specific paper, but I remember reading articles and watching a few talks from Chris Lattner about LLVM and just being like wow... I then got involved with LLVM libc over the summer, and, while a new libc is a difficult endeavor, I found their design philosophy to be brilliant. It is truly amazing how talented some of the LLVM contributors are.

**Is there a specific grad student or a project you're interested in working on?**
Anything LLVM/MLIR related would be cool. I am very, very far from a MLIR expert, or even novice. In fact, I made my first contribution to CIRCT the other day. I am currently assisting with optimizing some canonicalization patterns for RTL. This began with me posting on Discourse one day and saying "Hey, I want to contribute!"

**Anything else you want to tell us about yourself?**
To be straightforward, I am new to the formal research realm. I am not the next Alan Turing of my generation (sorry Mom!). With that said, I am independent and persistent. I consider myself a good team member, and communicate well.

**Attach a CV if you like.** 
My Github contains some of my recent work on personal projects (and just like any good personal project, none are finished). For my industry background, I've interned at Google twice, working for the Google Infrastructure team and the Google Ads team. I also assisted with LLVM libc, which is spearheaded by Google engineers. For my work this past summer, I received two peer bonuses.

**Comment by rachitnigam** [comment]
Hey Chris, Thanks for reaching out! We're currently thinking about porting [FuTIL](https://github.com/cucapra/futil/) to MLIR (and are also a part of the CIRCT group).

Can you send me an email at rnigam@cs.cornell.edu so we can setup a time to chat?

**Comment by cgyurgyik** [comment]
Will do.
