### ISSUE TITLE
Jackson Fellows

### ISSUE THREAD

**Issue by jacksonfellows** [cucapra/undergrad-research#48]
## Personal Details

**Name**: Jackson Fellows

**Major**: Undeclared

**Year in Cornell**: Freshman

**Relevant classes**: CS 2112 (currently enrolled)

**Interested in continuing research during the summer:** Maybe

## Research

**When do you want to do research?**
I am interested in doing research during the spring semester (or winter if that is a possibility).

**What is exciting to you about research?**
I have always enjoyed learning about programming languages. It is fascinating to me how different languages and paradigms can facilitate entirely different thought processes while developing code. For example, after learning Haskell I have had an entirely different mindset while programming, even in other languages. I am intrigued by your research group as you are exploring how to build new languages as tools for the efficient (and safe) utilization of hardware. While I have been exposed to different languages as new tools of thought, I am excited to expand my knowledge about how they can help us better use the underlying hardware that powers all of our devices.

**What kind of research do you want to do?**
As I mentioned above, I am interested in working on programming languages. However, that seems to apply to almost everything Capra is doing, so I am not entirely sure exactly which project would be the best fit.

## Background

**Was there a paper that particularly excited you?**
One paper that I found interesting is [An Incremental Approach to Compiler Construction](http://scheme2006.cs.uchicago.edu/11-ghuloum.pdf). After reading it, I was inspired to work on a [toy Scheme compiler](https://github.com/jacksonfellows/scheme-from-scratch) of my own. While I made some different decisions than the author (e.g. targeting C instead of assembly), I adopted his approach of starting with trivial cases (e.g. compiling integer constants) and gradually increasing language complexity.

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**
I may not have a formal background in the fields that your group in working on, but I do have a lot of experience in software development (software engineering intern at VMware for the past 4 summers), and am willing (and excited) to dive deep into new and unfamiliar topics.

**Attach a CV if you like.**
[JF-resume.pdf](https://github.com/cucapra/undergrad-research/files/5403533/JF-resume.pdf)

**Comment by Checkmate50** [comment]
Hi Jackson!  You have an interesting background in language work, but it's hard for me to tell if that will translate over to research.  My work focuses on language design for heterogenous device programming and compilation.  If this kind of research sounds interesting, can you send me an email at dag368@cornell.edu so we can setup a time to chat in person?

**Comment by Checkmate50** [comment]
I'm going to close this since our initial working together is going well, but feel free to reopen if you want to move.
