### ISSUE TITLE
Iain Pile

### ISSUE THREAD

**Issue by titan-mnemosyne** [cucapra/undergrad-research#49]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Iain Pile

**Major**: CS

**Year in Cornell**: Senior

**Relevant classes**: CS 3110, CS 3410, CS 4120, CS 4410, CS 4820

**Interested in continuing research during the summer:** Yes, if that's possible

## Research

**When do you want to do research?**
I imagine it's a bit late to get involved in research this semester, but would love to if that's possible! Or next semester.

**What is exciting to you about research?**
After taking compilers last semester, as well as from learning a bit about the logic behind languages in 3110 and 4110 this semester, I’ve been wanting to get a more in depth look at the area of programming languages, both on a theoretical and technical level. Outside of classes, I don’t have much experience working with computer science in a formal academic environment, so seeing what kinds of technologies and projects the theory I’m learning in classes can be applied to appeals to me.

**What kind of research do you want to do?**
Something involving compilers, most likely, as I’m interested in applying some of what I learned in that course to research. Of course, I wouldn’t mind working with more theoretical aspects of research as well, as I haven’t had much formal exposure there besides reading up on my own time.

## Background

**Was there a paper that particularly excited you?**
I was particularly interested in _Traits: Composable Units of Behavior_, about Rust's alternative to object-oriented programming. Type systems, and the various way program languages work with them, are one of my primary areas of interest.

**Is there a specific grad student or a project you're interested in working on?**
Not in particular. FuTIL and Dahlia seem interesting, but any project works for me. I'm looking to try anything.

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**

**Comment by Checkmate50** [comment]
Hey Iain!  I'm working on developing heterogeneous types for a graphics compiler and feel like you have a great background for working on this project.  If you're interested, could you send me an email at dag368@cornell.edu so we can setup a time to chat in person?
