### ISSUE TITLE
Karl Mobed

### ISSUE THREAD

**Issue by KarlMobed** [cucapra/undergrad-research#5]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here is [an example](https://github.com/cucapra/undergrad-research/issues/1) of a filled out template for reference.

## Personal Details

**Name**:Karl Mobed

**Major**:Computer Science and History

**Year in Cornell**:Sophomore

**Relevant classes**:CS 3110, CS 3410

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I would like to start research over the summer of 2019.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I have always enjoyed working with the most basic elements of a topic and figuring out new ways ways to use them to create more complicated systems.  This is the aspect that I always loved about history research because history is all about recombining the smaller facts, statistics, names, etc and creating new approaches to and views of the past. Computer science first appealed to me because coding relied on creating such intricate systems with relatively simple tools.  Computer architecture and language design are both extremely exciting because they not only both let me work on a new level of complexity but they also are extremely interconnected.  I want to work at a level where the bridge between hardware and software is close enough that I can use both to solve problems.

**What kind of research do you want to do?**
I do not know exactly what I want to do; I am looking to explore.  I do find language interpreters and how they directly lead/relate to home a computer's pipeline and processing very exciting.

## Optional Stuff

**Was there a paper that particularly excited you?**
I read a  paper recently on zero-knowledge proofs for the Ethereum digital currency, although I cannot find a link for it, that could go a long way towards solving blockchain's power problem.  While I am skeptical as the technology's use for digital currencies, zero-knowledge proofs could make the process of creating new blocks much more power efficient, making the process cheaper and more accessible to other fields while not compromising its security.  
 
**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**
I study both computer science and history, and I always look for ways to combine my interests.  While many of the organizations I am involved in like the Creative Computing Club or the Cornell Historical Society rarely overlap, I find that they remain relevant to each other.  For example, I've been looking at the possibilities of ternary computing systems, and history is a great source to draw from because a lot of interesting mathematical work was done before the physical practicality of a circuit forced binary.   

**Attach a CV if you like.**
[Karl Mobed Resume Research.pdf](https://github.com/cucapra/undergrad-research/files/3087761/Karl.Mobed.Resume.Research.pdf)

**Comment by sampsyo** [comment]
Hi! If you’re still looking for something to do over the summer, we have something pretty specific we could use help with.

We’re working on this [programming language for custom hardware accelerator design](https://github.com/cucapra/seashell). It uses a fancy type system to provide guarantees about how the hardware implementation corresponds to an algorithmic specification. The compiler is working and we’re making progress on implementing a suite of benchmarks, and we could use help with one of two things:

1. **Porting to [AWS F1][f1].** Our toolchain currently runs on a single FPGA we have in the lab, but we would love to be able to run on a larger FPGA in the cloud—and to let other people use the language just by spinning up a VM. Your task would be to learn about how AWS and F1 works, bring up our current toolchain there, write lots of supporting tooling to make this all work, and thoroughly document the process so anyone can get started using our language. This would be good for anyone but especially good if you’re interested in cloud computing.
2. **An [Intel HLS][ihls] backend.** Our compiler currently targets the [Xilinx][] ecosystem, but it should also hypothetically work just as well for Intel FPGAs. We want to build a new backend for our compiler that emits the OpenCL code that the Intel toolchain takes as an input. This task would be especially good if you are interested in learning about compiler hacking. Our compiler is implemented in Scala, so it would also be an opportunity to learn that language.

Do either of those appeal? Let us know and we’ll talk more!

[f1]: https://aws.amazon.com/ec2/instance-types/f1/
[xilinx]: https://www.xilinx.com
[ihls]: https://www.intel.com/content/www/us/en/software/programmable/quartus-prime/hls-compiler.html

**Comment by KarlMobed** [comment]
Hello,
 Thank you for your response.  I am still looking for research, and the Intel HLS backend sounds very appealing to me.
Karl

**Comment by sampsyo** [comment]
Neat! Let's talk in person about it more. Are you around next week after classes end (i.e., Wednesday through Friday)?

**Comment by KarlMobed** [comment]
Hello!  I am actually not around that time because I am presenting some research in Washington DC from May 8 to 11.  Can you meet before or after those days?

**Comment by sampsyo** [comment]
The week after would work well!

**Comment by KarlMobed** [comment]
Sounds good.  I am pretty flexible that week, so when is it convenient for you to meet?

**Comment by sampsyo** [comment]
How about 2:30pm on Monday? I'll also invite @rachitnigam.

**Comment by KarlMobed** [comment]
I, unfortunately, have a final at that time. I should specify that I am flexible all that week other than Monday and after 6 Pm on Wednesday.  I hope this is not too inconvenient for you

**Comment by sampsyo** [comment]
OK! @rachitnigam, would any time on Tuesday or Wednesday work for you?

**Comment by rachitnigam** [comment]
Yeah. Anytime will be fine. I prefer mornings.

**Comment by sampsyo** [comment]
Alright! How about 10am on Tuesday?

**Comment by KarlMobed** [comment]
That sounds perfect

**Comment by sampsyo** [comment]
Great; see you in my office (411A).

**Comment by rachitnigam** [comment]
Hi Karl, can you send me your preferred email and Github ID so I can add you to relevant groups and our slack?
