### ISSUE TITLE
Andrei Shpilenok

### ISSUE THREAD

**Issue by ashpil** [cucapra/undergrad-research#50]
## Personal Details

**Name**: Andrei Shpilenok

**Major**: Technically undecided, but planning to affiliate with CS

**Year in Cornell**: Sophomore

**Relevant classes**: CS 3110, CS 4110, CS 4625. Hoping to take CS 5625 and CS 3410 in the spring (but already have previous experience with assembly and low-level programming).

**Interested in continuing research during the summer:** Yup!

## Research

**When do you want to do research?**
As soon as possible! Ideally throughout next semester, and in the summer if it goes well. 

**What is exciting to you about research?**
It's amazing that computer science, as a field, has only been around for like 100 years are so. Among other sciences, this is relatively immature, so it's really cool how many things are left undiscovered. I'm especially interested in optimization - getting things to run as efficiently as possible, which often involves delving deep into the hardware details and then abstracting up to make those deep-dives smoother in the future. 

**What kind of research do you want to do?**
I'm much more interested in the hands on stuff - implementing demos and writing code than theoretical discussion and proofs (though those can be fun too, if I'm interested in the underlying topic!). I'm really interested in computer graphics (but not vision), as well as programming languages - but less so the formal semantics and more so the aesthetics and usability parts. 

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
Unfortunately, I don't have a prior background in CS research so anything I could list here I'd just be finding now. 

**Is there a specific grad student or a project you're interested in working on?**
I just learned of this research group today in my 4110 class, where Alexa and Dietrich both talked about their projects, which are both very cool! Ideally I'd be involved in something low-level or graphics-focused, and has hands-on work to be done.

**Anything else you want to tell us about yourself?** Please check out my GitHub! I spend a lot of time working on my personal projects. Two that are especially relevant (both wip) are [a unix shell](https://github.com/ashpil/rush) (that's a programming language!) and a [path tracer](https://github.com/ashpil/syzygy).

**Attach a CV if you like.**
[Of course!](https://github.com/cucapra/undergrad-research/files/5681430/Andrei_Shpilenok_Resume.pdf)

**Comment by Checkmate50** [comment]
Hey Andrei!  Could you send me an email at dag368@cornell.edu so we can set up a time to chat in person?
