### ISSUE TITLE
Eric Jackson

### ISSUE THREAD

**Issue by EricJackson314** [cucapra/undergrad-research#51]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Eric Jackson

**Major**:  Computer Science and Mathematics

**Year in Cornell**: Sophomore

**Relevant classes**: CS 3110, CS 4110

**Interested in continuing research during the summer**: Yes

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)

I am open to, and excited about, doing research during the semester or during the summer. Ideally, I could begin in the spring and, if things work out, continue into the summer.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)

I enjoy the satisfaction that comes from finding elegant solutions to hard problems. Research presents a great opportunity for me to do this. Additionally, I am considering a PhD. Undergraduate research is an awesome way for me to see if this the right thing for me.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")

I'm happy to explore, but I have a particular interest in issues related to programming languages.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

**Is there a specific grad student or a project you're interested in working on?**

Dietrich Geisler presented on GATOR during a CS 4110 lecture. I would be interested in working on that project.

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[resume1.pdf](https://github.com/cucapra/undergrad-research/files/5732034/resume1.pdf)

**Comment by Checkmate50** [comment]
Hey Eric!  I'm actually interviewing people to figure out a good fit for the Gator project this week; could you send me a message at dag368@cornell.edu to organize a time to chat virtually?

**Comment by Checkmate50** [comment]
Eric found a research project from what I understand, so I'll close this issue.  Let me know if you want it reopened.
