### ISSUE TITLE
Jonathan Tran

### ISSUE THREAD

**Issue by JonathanDLTran** [cucapra/undergrad-research#52]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**:
Jonathan Tran
**Major**:
Computer Science, Statistics
**Year in Cornell**:
4th year
**Relevant classes**:
CS 4110, CS 3110, CS 3410, CS 4820, CS 4414
**Interested in continuing research during the summer:**
I am interested in continuing research during the summer.

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I want to start with research in Spring 2021.
**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I find it fascinating how type systems can be used to eliminate certain errors with certainty. I am excited to learn more about how different type systems can be used in various applications.
**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I took CS 4110 and found a lot of the topics to be very interesting, especially type systems and translation. I would love to explore any area though!

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
I thought the paper on Opal was particularly interesting in how it separates hypothetical world actions and allows committing of the actions. I also thought the idea of using types for the domain specific language to be quite interesting, as it could allow the client compiler to check all possible variants in a type. I am wondering if the techniques in the paper could be expanded to further areas in AI, other than natural language.
**Is there a specific grad student or a project you're interested in working on?**
I read about the Dahlia project and found it quite interesting how resource usage can be protected from conflicting uses, and how Dahlia can force the programmer to choose a design that will not require many compiler transformations.
I also found the Gator project interesting, especially on how the geometric incompatibility can be detected at compile time.

**Anything else you want to tell us about yourself?**
I have been working on a compiler for a simple programming language that I designed last summer. I was playing around with building a parser, lexer, semantic analysis and code generation into Risc-V. I'm now looking into designing an intermediate representation and optimizations for the compiler. 
**Attach a CV if you like.**
[CSResume12:11:2020.pdf](https://github.com/cucapra/undergrad-research/files/5743960/CSResume12.11.2020.pdf)

**Comment by avanhatt** [comment]
Hi Jonathan, we are looking for undergraduate researchers to work on Diospyros, a synthesizing compiler for digital signal processors (you can read a 2 page extended abstract on the work [here](https://asplos-conference.org/abstracts/asplos21-paper142-extended_abstract.pdf)). In particular, we have some work compiling from general-purpose C/C++ code to our domain specific language that sounds aligned with your interest in translation semantics. 

If this sounds interested to you, please email me at avh@cs.cornell.edu with your availability and we can set up a time to talk. Thanks!
