### ISSUE TITLE
William Ma

### ISSUE THREAD

**Issue by whoiswillma** [cucapra/undergrad-research#53]
## Personal Details

**Name**: William Ma

**Major**: Computer Science

**Year in Cornell**: 3rd Year

**Relevant classes**: CS 3110, ECE 2300, CS 3420, CS 4120

**Interested in continuing research during the summer:** Yes

## Research

**When do you want to do research?** Spring 2021

**What is exciting to you about research?** I want to work on new tools or develop systems for other humans to solve problems in new ways. Specifically, programming languages and libraries that cleanly and correctly express ideas are the most exiting to me. It's not just that a tool can solve a problem, but that it solves the problem elegantly.

**What kind of research do you want to do?** Not sure. Compiler work sounds the most interesting to me thought that may just be what I'm most familiar with

## Background

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

I implemented the algorithm described in [this paper](https://dl.acm.org/doi/10.1145/229542.229546) to perform iterated register allocation for CS 4120. This paper I felt touched upon every part of my computer science education up until that point: Graph coloring and NP-complete problems, hardware and assembly, and proof-based reasoning. It was also exiting to see program performance increase significantly after register allocation.

More recent (not a paper but still technical) is [a proposal for function builders](https://github.com/apple/swift-evolution/blob/9992cf3c11c2d5e0ea20bee98657d93902d5b174/proposals/XXXX-function-builders.md) in Swift. Although this proposal's stated purpose is clear, for me it instead highlighted the inherent tension between control flow and expressions in language design. 

**Is there a specific grad student or a project you're interested in working on?** After poking around on the website for a while, I'm interested in working on Dahlia and Gator

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**

**Comment by Checkmate50** [comment]
Hey William!  If you're still interested in a research project, could you send me an email at dag368@cornell.edu so we can chat?

**Comment by Checkmate50** [comment]
Closed due to finding other research.  Feel free to reopen if something changes!
