### ISSUE TITLE
Jasper Liang

### ISSUE THREAD

**Issue by jasperxfliang** [cucapra/undergrad-research#54]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Jasper Liang

**Major**: Computer Science & Math

**Year in Cornell**: Junior

**Relevant classes**: CS 3110, CS 3410, CS 4110, CS 4410, CS 4670, CS 4820

**Interested in continuing research during the summer:** Yes

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I would love to start research in the Spring or Summer.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
During 4110, we went back to the fundamentals of how programming languages worked, and I was fascinated by how techniques such as encodings and translations could be customized to solve problems or make code more user-friendly. I hope that through research, I will be able to solve problems in programming languages that will improve or solve problems in industries and beyond.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I am open to anything, but do have a lot of interest in programming languages and computer vision.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
My friend mentioned a [paper](https://www.cs.cornell.edu/~jnfoster/papers/petr4.pdf) he worked on with Prof. Foster -- it was neat to see a real-world example for how learning tons of definitions and semantics of programming language logic in 4110 could actually be used creatively to solve problems in other areas such as networking.

**Is there a specific grad student or a project you're interested in working on?**
The Gator project initially interested me when it was presented during class because I had taken computer vision before, but I would love to work on anything with Capra.

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**

**Comment by avanhatt** [comment]
Hi Jasper, we are looking for undergraduate researchers to work on Diospyros, a synthesizing compiler for digital signal processors (you can read a 2 page extended abstract on the work [here](https://asplos-conference.org/abstracts/asplos21-paper142-extended_abstract.pdf)). In particular, we have some work compiling from general-purpose C/C++ code to our domain specific language that has some overlap with the translations covered in 4110.

If this sounds interesting to you, please email me at avh@cs.cornell.edu with your availability and we can set up a time to talk. Thanks!

**Comment by jasperxfliang** [comment]
Thanks for the reply, I just sent you an email. :)
