### ISSUE TITLE
Shi Chong Zhao

### ISSUE THREAD

**Issue by shichong-97** [cucapra/undergrad-research#56]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**:
Shi Chong Zhao

**Major**:
Computer Science, Cognitive Science (minor)

**Year in Cornell**:
Junior/Senior (accelerating my graduation by a year so this is my last semester)

**Relevant classes**:
Completed: CS 3110 (A), CS 3410 (A+), CS 4120 (A), CS 4410 (A+), CS 5414 (A-)
Enrolling this semester: CS 4411, CS 5412

**Interested in continuing research during the summer:**
I will be back in Singapore this summer and I would have graduated by then, but I will still be happy to do research if I can!

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I will like to do research for this semester (Spring 2021), and if possible virtually, Summer 2021 will be great too!

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
My interest in research stems from some little fascinations of mine: the possibility of computationally modelling a human brain, the probability of projecting ourselves, personality and memories and all, onto a digital platform, and the prospect of having our feelings and experiences shared "telepathically" with other people. As a minor in Cognitive Science, I know that we are still very far from realizing any of my fascinations; we are still the stage where we are trying to model an organism as simple as C. elegans. As of now, I don't believe any of my imaginations will become a reality within my lifetime, but if it is possible for even a small part of it to become real, I want to be a part of the team that achieves that. I recently had a discussion with a professor regarding whether or not to apply for Ph.D, and he describes embarking on a Ph.D as treading on a path that no one else has set foot on, and seeing beautiful sceneries that no one else has ever seen. Even though I eventually decided to hold off on applying to Ph.D until I actually accumulate some research experience (which is why I am applying to CAPRA), the thought of being able to experience something that no one else ever has excites me greatly.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
After taking a substantial number of CS courses at Cornell, learning numerous new programming languages including Java, Kotlin, C++ etc., I find myself more fascinated by what lies at the lower-level of computing, such as how human-written code gets translated into machine code and how processors take the code and physically perform the operations that are required of them. I feel that at the end of the day, even though new programming languages are being created regularly and existing programming languages are constantly being expanded on, it is really what goes on down there in the chip that gives us the power to do what we can on a computer. I had a ton of fun building my virtual RISC-V processor when I was enrolled in CS 3410, and the programming assignments for CS 4120 were nothing but challenging to say the least. I do not know enough to be aware of how close actual research will be like these assignments, but these are the general areas that I will like to be involved in. 

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
Not sure if it is relevant to what is done in this group, but when I was in CS5414 Professor Alvisi introduced us to a paper called "Paxos Made Moderately Complex", written by Professor Robbert van Renesse, another professor here at Cornell. CS5414 made me truly understand the difficulty of achieving consensus across multiple processors, a problem made more difficult with asynchrony as well as unreliable networks. Paxos was a protocol proposed to solve the problem and the way that the paper introduced the protocol was so fascinating that I was laughing inside while being utterly amazed by the elegance of the protocol and how despite its apparent complexity, the protocol makes a lot of intuitive sense once one takes the time to grind over it.

**Is there a specific grad student or a project you're interested in working on?**
As of current, I am most interested in working on either Dahlia or FuTIL because they seem to align most with the kind of research that I want to do; the kind which goes really in-depth into the connections between software and hardware.

**Anything else you want to tell us about yourself?**
I guess what I want to say the most is that because of my goal to graduate in three years rather than four (a year of stay at Cornell ain't exactly cheap), I was much more focused on completing my course requirements and preparing myself for working instead of engaging in research. Therefore, my expertise is definitely much more geared towards the private industry rather than the academics, and I frankly do not have much research experience to speak of. However, now that I am in my final semester and I have quite literally cleared all of my graduation requirements apart from a single course, I feel that I want to dedicate my time to research since it is something I do have an interest in but never really experienced, and might have little chance to experience again once I start working in the private industry (I am also working towards achieving CS Honors!). Therefore, I view this as my last chance to steer my career direction towards the academics. I hope to experience what engaging in research feels like, and if I find myself to be well-suited for it, I aim to apply to Ph.D in the upcoming cycle even after I have started working. This is something I am willing to dedicate a lot of my time and effort this semester to, and I will really appreciate it if I could be given the opportunity to be part of this research team.

**Attach a CV if you like.**
I have attached both my resume/CV and transcript because I feel that my transcript might be more informative than my resume with regards to my competency for research.

[Resume (Fall 2020).pdf](https://github.com/cucapra/undergrad-research/files/5942854/Resume.Fall.2020.pdf)
[FA 2020 Transcipt.pdf](https://github.com/cucapra/undergrad-research/files/5942853/FA.2020.Transcipt.pdf)

**Comment by rachitnigam** [comment]
Hey @shichong-97! I assume you've graduates so I'm closing this. If that's not the case and you're still interested, let us know.
