### ISSUE TITLE
YoungSeok Na

### ISSUE THREAD

**Issue by yn224** [cucapra/undergrad-research#58]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: YoungSeok Na

**Major**: ECE & CS

**Year in Cornell**: Junior

**Relevant classes**:
Taken: CS 3110, CS 3420, CS 4420
Currently Enrolled: CS 4120, CS 4410, CS 4670

**Interested in continuing research during the summer:** Yes

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I would like to start research as soon as this semester.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
My interest in research in general began with a pure curiosity and want to learn more about computer architecture after taking the course ECE 2300. With my fixation with computer systems, I took courses that seemed relevant to my interest and I stumbled upon the topic of synthesis. After investigating more, I realized that the field of computer architecture was more than just a field that considers the efficiency of hardware composition. But there were limitations as to how much I could learn about it as an undergraduate. Yet, I believe that is why research exists. For me, research provides new materials that I could learn from and brings fulfillment by providing a final picture using small efforts I have made in the past. I am hoping that through this research experience, I could have enough opportunities to expose myself to the developmental process of synthesis tools. Also, I hope that the experiences I gained through the process could enable me to contribute to the development of the computer systems field.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I would like to get involved in a research where I can get to expand my knowledge in synthesis languages.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
The paper that particularly caught my eye was the paper "[Predictable Accelerator Design with Time-Sensitive Affine Types](https://www.cs.cornell.edu/~asampson/media/papers/dahlia-pldi2020.pdf)". Among many papers out there, the fact that this paper introduces a programming platform that tries to lower the barrier of HLS attracted me.

**Is there a specific grad student or a project you're interested in working on?**
As there was only one project that struck me the most, I would like to get involved in the Dahlia project.

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[YoungSeok_Na_Resume.pdf](https://github.com/cucapra/undergrad-research/files/5968693/YoungSeok_Na_Resume.pdf)

**Comment by rachitnigam** [comment]
Hey @yn224, can you send me an email with your availability next week?

**Comment by yn224** [comment]
Thank you for getting back! Just sent an email to you.
