### ISSUE TITLE
[Andrii Iermolaiev]

### ISSUE THREAD

**Issue by ai-cu** [cucapra/undergrad-research#59]
## Personal Details

**Name**: Andrii Iermolaiev

**Major**: CS

**Year in Cornell**: '23 (Sophomore)

**Relevant classes**: CS3110, ECE2300, CS3420

**Interested in continuing research during the summer:** Yes

## Research

**When do you want to do research?**
Start this summer and resume in Fall 21

**What is exciting to you about research?**
I have never done any CS related research, but I did do physics research. My first research experience was at 15, and I have really missed it since. What I appreciate most about it is the freedom but also the mentorship that comes with it. 

I have held a formal internship my freshman summer, but the cognitive challenge was not as rewarding, which is why I am heavily interested in doing research. 

Now about PL interest:
I am currently in CS4670 and we are using Python, which I haven't used for a year. I did not expect that getting back to it will make me so disappointed.
Doing matrix operations using loops is so non-elegant; I do miss static typing too (which I know can't work for python since its interpreted but still). The differences between all the languages are so intriguing.
That made me recently interested in the PL field and I started reading some papers. I read up on Lambda Calculus and starting to go through some of the textbooks recommended by CS4110. So far the topic seems very fascinating and I want to delve deeper.

**What kind of research do you want to do?**
Having read through the Capra website, I am most interested by Dahlia, since a language with a structural type system for FPGA design seems like a very smart idea and I would love to contribute to something that makes FPGA design more straightforward; and Braid, since I recently became interested by real-time graphics issues and Braid seems like a very clever approach.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
Not a paper, but the videos on Dahlia by Adrian and Rachit are very informative and well made.

**Is there a specific grad student or a project you're interested in working on?**
Dahlia and Braid as said above, but I would love to work on any other project where my help could be of use.

**Anything else you want to tell us about yourself?**
I am a fast learner and am ready to dedicate a significant chunk of my time to this since I am heavily considering PL research as a future career.

**Attach a CV if you like.**

[ai93_curr_resume_tech.pdf](https://github.com/cucapra/undergrad-research/files/6056213/ai93_curr_resume_tech.pdf)

And just as a living proof of me always being obsessed with science and cool ideas here's a video of me at 14 talking about quantum loop gravity and string theory (not CS but I didn't really know anything about computers back then either):

https://user-images.githubusercontent.com/71833057/109528357-95a6b600-7a82-11eb-9675-bd9bef7d585c.mp4

**Comment by rachitnigam** [comment]
Hey @ai-cu, just to confirm, you're not planning to start research this semester?

**Comment by ai-cu** [comment]
@rachitnigam I could potentially, if there's an opportunity. I would also be very happy studying up on everything that I might need to know before the summer to successfully start working within the group.

**Comment by rachitnigam** [comment]
Cool. Send me an email at rnigam@cs.cornell.edu with your availability for this week and the next and we can chat.

**Comment by ai-cu** [comment]
@rachitnigam email sent! Thank you
