### ISSUE TITLE
Yuwei Ye

### ISSUE THREAD

**Issue by ViviYe** [cucapra/undergrad-research#6]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here is [an example](https://github.com/cucapra/undergrad-research/issues/1) of a filled out template for reference.

## Personal Details

**Name**: Yuwei Ye

**Major**: Computer Science

**Year in Cornell**: Freshmen (Rising Sophomore)

**Relevant classes**: CS 2112, CS 2800, CS 3110, ECE2300

## Research

**When do you want to do research?**
I would love to start during summer 2019!

**What is exciting to you about research?**
I got super excited about research after a chance to talk to graduate students! I believe research can serve as a good platform for me to learn deeper and faster. I would love to dedicate myself to exploring new fields and solving real-world problems. Everyone tells me "research has ups and downs". I think I would definitely enjoy this process: I found nothing more rewarding than solving a problem eventually despite all the challenges.
From participating in research, I aim to explore the fields I am most interested in, and learn from other team members!

**What kind of research do you want to do?**
I am new to research so I am looking to explore!
After taking ECE2300, and CS2800, I became intrigued by how software and hardware interact to achieve a complex, but efficient system. The idea software-hardware codesign interests me. I would love to learn more about approximate computing and it's application into different fields of computer science.

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
I recently read a paper about reconstructing realistic images from fMRI data, using the convolutional neural network (CNN) and generative adversarial network (GAN). The research found out we can recreate with surprising accuracy the image we are looking at just from processing fMRI data. I am super excited about the unlimited potential of computer vision and how all the scientific fields are interconnected.

**Is there a specific grad student or a project you're interested in working on?**
The approximate vision project and the lambda lab project interest me a lot!
Even though I don't have extensive experience in either field, I found the projects interesting and powerful. I am excited to learn more about vision or lambda algebra.

**Anything else you want to tell us about yourself?**
I am interested in CS, ECE, cognitive science, and traditional Chinese instruments. I love learning and exploring new fields!

**Attach a CV if you like.**
Here is my resume attached!
[YuweiYe_resume.pdf](https://github.com/cucapra/undergrad-research/files/3100645/YuweiYe_resume.pdf)

**Comment by sampsyo** [comment]
Hi! If you’re still looking for something to do over the summer, we have something pretty specific we could use help with.

We’re working on this [programming language for custom hardware accelerator design](https://github.com/cucapra/seashell). It uses a fancy type system to provide guarantees about how the hardware implementation corresponds to an algorithmic specification. The compiler is working and we’re making progress on implementing a suite of benchmarks, and we could use help with one of two things:

1. **Porting to [AWS F1][f1].** Our toolchain currently runs on a single FPGA we have in the lab, but we would love to be able to run on a larger FPGA in the cloud—and to let other people use the language just by spinning up a VM. Your task would be to learn about how AWS and F1 works, bring up our current toolchain there, write lots of supporting tooling to make this all work, and thoroughly document the process so anyone can get started using our language. This would be good for anyone but especially good if you’re interested in cloud computing.
2. **An [Intel HLS][ihls] backend.** Our compiler currently targets the [Xilinx][] ecosystem, but it should also hypothetically work just as well for Intel FPGAs. We want to build a new backend for our compiler that emits the OpenCL code that the Intel toolchain takes as an input. This task would be especially good if you are interested in learning about compiler hacking. Our compiler is implemented in Scala, so it would also be an opportunity to learn that language.

Do either of those appeal? Let us know and we’ll talk more!

[f1]: https://aws.amazon.com/ec2/instance-types/f1/
[xilinx]: https://www.xilinx.com
[ihls]: https://www.intel.com/content/www/us/en/software/programmable/quartus-prime/hls-compiler.html

**Comment by ViviYe** [comment]
Thank you so much for offering me these potential opportunities!
I looked into F1 instances and became fascinated by the idea " FPGA in the cloud". I would love to learn more about the process, by helping with porting to AWS F1. I am still available for most of the summer. It will be great if we can talk more about the opportunity to work on this project! Is there any specific person I should contact for more information?

**Comment by ViviYe** [comment]
> Hi! If you’re still looking for something to do over the summer, we have something pretty specific we could use help with.
> 
> We’re working on this [programming language for custom hardware accelerator design](https://github.com/cucapra/seashell). It uses a fancy type system to provide guarantees about how the hardware implementation corresponds to an algorithmic specification. The compiler is working and we’re making progress on implementing a suite of benchmarks, and we could use help with one of two things:
> 
> 1. **Porting to [AWS F1](https://aws.amazon.com/ec2/instance-types/f1/).** Our toolchain currently runs on a single FPGA we have in the lab, but we would love to be able to run on a larger FPGA in the cloud—and to let other people use the language just by spinning up a VM. Your task would be to learn about how AWS and F1 works, bring up our current toolchain there, write lots of supporting tooling to make this all work, and thoroughly document the process so anyone can get started using our language. This would be good for anyone but especially good if you’re interested in cloud computing.
> 2. **An [Intel HLS](https://www.intel.com/content/www/us/en/software/programmable/quartus-prime/hls-compiler.html) backend.** Our compiler currently targets the [Xilinx](https://www.xilinx.com) ecosystem, but it should also hypothetically work just as well for Intel FPGAs. We want to build a new backend for our compiler that emits the OpenCL code that the Intel toolchain takes as an input. This task would be especially good if you are interested in learning about compiler hacking. Our compiler is implemented in Scala, so it would also be an opportunity to learn that language.
> 
> Do either of those appeal? Let us know and we’ll talk more!

Thank you so much for offering me these potential opportunities!
I looked into F1 instances and became fascinated by the idea " FPGA in the cloud". I would love to learn more about the process, by helping with porting to AWS F1. I am still available for most of the summer. It will be great if we can talk more about the opportunity to work on this project! Is there any specific person I should contact for more information?

**Comment by sampsyo** [comment]
Neat! Let's set up a time to talk more in person. Are you around next week after classes end (i.e., Wednesday through Friday)?

**Comment by ViviYe** [comment]
Yes, I can meet anytime between Wednesday and Friday! When will be a good time to meet?

**Comment by sampsyo** [comment]
Great! How about Thursday at 10:30am? We can meet in my office, and I'll invite @rachitnigam too.

**Comment by ViviYe** [comment]
That works for me! Thank you so much!

**Comment by rachitnigam** [comment]
@ViviYe Hey! Sorry to miss our meeting. I'm in my office (gates 305) till 1.15. Just come by if you'd like to talk a bit more.

**Comment by rachitnigam** [comment]
Hi Yuwei, can you send me your preferred email and Github ID so I can add you to relevant groups and our slack?

**Comment by ViviYe** [comment]
My GitHub ID is ViviYe
and my slack was registered with Cornell email yy453@cornell.edu!

Thank you so much!

**Comment by rachitnigam** [comment]
Great! You should get an invitation to join our research slack. Please join the #seashell and #fuse-students channels!
