### ISSUE TITLE
Haoxuan Chen

### ISSUE THREAD

**Issue by chx125ck** [cucapra/undergrad-research#60]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Haoxuan Chen

**Major**: Computer Science

**Year in Cornell**: 3rd year

**Relevant classes**: cs 2110, cs 3110, cs 3410, cs 4620, cs 4621

**Interested in continuing research during the summer:**

## Research

**When do you want to do research?**
I want to do research starting the end of this semester and continue in summer.

**What is exciting to you about research?**
During my 3 years of studying in college, I feel like that most of the things we have in courses is just learning the basic ideas of certain areas, and I want to learn how exacty these ideas were developed and get involved in actually doing something new and useful.

**What kind of research do you want to do?**
I'm interested in computer graphics.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
Casting curved shadows on curved surfaces (https://dl-acm-org.proxy.library.cornell.edu/doi/10.1145/965139.807402) was really exciting to me. It was a pretty old paper on rendering techniques with rasterization pipeline and the idea of treating the lights as cameras and using their depth map to determine shadows was really fascinating.

**Is there a specific grad student or a project you're interested in working on?**
I talked to Dietrich about the slang project, but I am also willing to work on other projects.

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**

**Comment by Checkmate50** [comment]
Hey Haoxuan!  Could you send me an email at dag368@cornell.edu so we can chat about potential research?  Thanks!
