### ISSUE TITLE
Zachary Kent

### ISSUE THREAD

**Issue by zachary0kent** [cucapra/undergrad-research#64]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Zachary Kent

**Major**: Computer Science

**Year in Cornell**: Rising 2nd year

**Relevant classes**:
Completed: CS 2110, CS 2800, ECE 2300, ECE 3140 / CS 3420
Taking Fall 2021: CS 3110, ECE 4750 / CS 4420

**Interested in continuing research during the summer:**
Definitely!

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I'd be able (and delighted!) to start research as soon as possible--i.e. this summer or the coming fall semester. After that, I'd love to continue research through Spring 2022 and full-time Summer 2022 as well. 

**What is exciting to you about research?**
I have always been engrossed by systems and low-level programming but, alas, have never been able to quite scratch that itch. The material from ECE 2300 and ECE 3140 only served to whet my appetite for more--I am beyond grateful for the foundational knowledge it provided me, but have always yearned for the opportunity to apply this theory to practical, relevant issues in Systems and Computer Architecture. I find the optimization of software performance through its development in tandem with hardware particularly fascinating--I know Capra is the ideal environment for me to explore my interests in the hardware-software boundary. 

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
Although I am definitely looking to explore, I have always been extremely fascinated by concurrency and parallelism--by far my favorite topics in CS so far. I am especially fascinated with implementing concurrency efficiently through optimal hardware design.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

**Is there a specific grad student or a project you're interested in working on?**
Although I’d be thrilled to work on any of Capra’s projects, I find Dahlia particularly interesting. The issue of the “semantic gap” between hardware and software strongly resonated with me--I find the idea of accurately modeling efficient hardware semantically highly stimulating. Furthermore, I have always wanted to explore programming languages and compilers, fields I would gain rich exposure to while working on Calyx and Dahlia.

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[Zachary Kent Resume.pdf](https://github.com/cucapra/undergrad-research/files/6698042/Zachary.Kent.Resume.pdf)

**Comment by rachitnigam** [comment]
Hey @zachary0kent! Can you email me at rnigam@cs.cornell.edu if you're still interested in doing research this semester?
