### ISSUE TITLE
[Evan Williams]

### ISSUE THREAD

**Issue by EvanWilliams02** [cucapra/undergrad-research#66]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Evan Williams

**Major**: ECE/CS

**Year in Cornell**: Sophomore (Class of 2024)

**Relevant classes**: Advanced C Programming (equivalent to CS 2110), ECE 2300 (Fall 2021), CS 3110 (Fall 2021), CS 2800 (Fall 2021)

**Interested in continuing research during the summer**: Potentially in Summer 2022

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I'd like to pursue research during the academic year, particularly for a long period of time (i.e. a full semester, year, or more). Depending on the state of my work, I'd also be interested in continuing over the summer. 

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I first started doing research as a senior in high school through my school's Mobile Web Development Research Lab. I worked at a higher level under Professor James Davis at Purdue University through the Duality Lab during my freshman year of college at Purdue. Here's the link to the site: https://davisjam.github.io/ 

I am intrigued by the uncertain nature of academic research. Unlike technical teams and clubs, you aren't always sure what the end result is going to be. I've found that doing research has made me a sharper programmer and academic. I'm more naturally inquisitive and I have to learn new technical skills quickly in order to discover something. I love the way research pushes me to better myself and hope to continue doing so at Cornell. 

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I'd love to do something that plays to my interests at the intersection of hardware and software. Computer architecture work is particularly interesting, though I don't have much experience in the field. Otherwise, I'd love to work on anything that pushes me to learn more about relevant fields in ECE and CS!

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
I personally really enjoyed reading "Reconfiguring the Imaging Pipeline for Computer Vision" (ICCV 2017). I took a computer vision course in high school and it was an interesting new approach to the more traditional topics I studied. 

**Is there a specific grad student or a project you're interested in working on?**
Not particularly!

**Anything else you want to tell us about yourself?**
Though I'm new to Cornell I'm eager to get involved! Research was my favorite activity at Purdue and I hope to continue doing this type of work. 

**Attach a CV if you like.**
[Evan-Williams-Resume-2021.pdf](https://github.com/cucapra/undergrad-research/files/6858808/Evan-Williams-Resume-2021.pdf)

**Comment by rachitnigam** [comment]
Hey @EvanWilliams02! Can you email me at rnigam@cs.cornell.edu so that we can setup a time to talk?
