### ISSUE TITLE
Yunus Maltiti Mohammed

### ISSUE THREAD

**Issue by yunusmohammed** [cucapra/undergrad-research#67]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Yunus Maltiti Mohammed

**Major**: Computer Science

**Year in Cornell**: Junior

**Relevant classes**: CS 3410 (Spring 2021), CS 3110 (FALL 2021)

**Interested in continuing research during the summer:** No

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
During semesters (FALL and SPRING) and I would like to start in Spring 2022 for credit

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
During the summer of 2020, I participated in the maiden edition of CSMore where various faculty members and  grad students had talks with us about the work they did. I was fascinated by the research most of them did and got interested in doing research sometime during my undergraduate studies. 

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I am mainly looking to explore. As a note however, after taking CS 3410 and liking the content, I would like to do some research in the domain of computer architecture. 

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
No, as of today.

**Is there a specific grad student or a project you're interested in working on?**
No.

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[Yunus_Maltiti_Resume.pdf](https://github.com/cucapra/undergrad-research/files/7011463/Yunus_Maltiti_Resume.pdf)

**Comment by rachitnigam** [comment]
> Was there a paper that particularly excited you?
> (This doesn't have to be a paper from our group.)
> No, as of today.

Hi @yunusmohammed. For Junior students and higher, we're looking to talk specifically about any papers you've already read because it'll give us a sense of the kind of research that interests you. You can [start with one of our projects](https://capra.cs.cornell.edu/) or read any other papers that sound interesting to you. Once you do that, please comment on this thread and let us know.

**Comment by rachitnigam** [comment]
Hi @yunusmohammed! I'm adding the "stale" label to your issue since it's currently missing required information. Please free to @ me once you've added that information.
