### ISSUE TITLE
[Boao(Mark) Dong]

### ISSUE THREAD

**Issue by markd88** [cucapra/undergrad-research#68]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Boao(Mark) Dong

**Major**: Computer Science

**Year in Cornell**: 3rd year

**Relevant classes**: CS4620, CS4670, CS4820, CS3110, CS2800, CS2110, CS1110, CS3410(Fall 2021), CS4414(Fall 2021)

**Interested in continuing research during the summer:** Yes, I am interested in continuing research next summer.

## Research

**When do you want to do research?**
I want to get started on research this semester, which is Fall 2021.

**What is exciting to you about research?**
To me, research means finding out the answer and creating a better way to solve the problems. When I interned as a software engineer, I really want to know how exactly the hardware supports or limits my program and if there are any better ways to organize hardware to work. So building new hardware-software interfaces appeals to me. In addition, I want to design useful things for people. When I saw Gator on the website, I could not help but think of the hard time of debugging my graphics project. Gator really identifies such a problem and offers a better solution. That is what I want to do!

**What kind of research do you want to do?**
I don't know yet, and I'm looking to explore! Currently, I am most excited about the research that involves the interactions between hardware and software. 

## Background

**Was there a paper that particularly excited you?**
I read the paper about Gator, and I think it is super cool. When I was first introduced to GLSL, I thought GLSL was so convenient. Although sometimes I still needed to figure out geometry when doing computation, I felt like GLSL was already "the best" language. After reading about Gator, I just realized that we could always make things better. For example, adding geometry types and automatic generations could help so much with Graphics. It pushes me to shift my mindset: doing research and trying to find a better way.

**Is there a specific grad student or a project you're interested in working on?**
I think Graphics Programming is cool, but I am interested in anything.

**Anything else you want to tell us about yourself?**
I am the type of person who is curious about technology improvement, and I am looking forward to expanding my knowledge and learning something new when doing research.

**Attach a CV if you like.**
[Boao(Mark)-Dong.pdf](https://github.com/cucapra/undergrad-research/files/7071658/Boao.Mark.-Dong.pdf)

**Comment by Checkmate50** [comment]
Hey Mark!  Could you email me at dag368@cornell.edu so we can chat about Gator and research projects?
