### ISSUE TITLE
Richard Wang

### ISSUE THREAD

**Issue by rich140** [cucapra/undergrad-research#69]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Richard Wang

**Major**: Computer Science

**Year in Cornell**: 4th year (last sem)

**Relevant classes**: Discrete Structures (2800), Functional Programming (3110), Computer Architecture (3410), Operating Systems (4410), Cloud Computing (5412), Computer Vision (4670). Currently taking Programming Languages (4110) and Systems (4414).

**Interested in continuing research during the summer:** Don't think this question is relevant, but if it is, I can answer.

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)

This semester (Fall 2021), preferably an independent study (CS4999) for credit. 

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)

I love learning, and I see research as a fantastic opportunity to learn! 

I also want to become more comfortable reading academic papers. I feel like they're sometimes esoteric and hard-to-read. 

Lastly, I want to make contributions that will help others - both Capra and the broader research community.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")

I don't know! I'm curious about a lot of things, and I'm looking to explore.

I chose Capra because (a) I enjoy topics such as recursion, peano arithmetic, optimization, (b) I'm interested in both PL and Computer Architecture, and (c) I'd like to fill my knowledge gaps in both these areas.

## Background

**Note**: If you're in your first or second year at Cornell, these are all optional. If you're a junior or senior, please answer the first two (the rest is still optional).

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

https://rachitnigam.com/files/pubs/dahlia.pdf
The idea that you can write code that optimizes for the underlying hardware is pretty intuitive, yet is something I rarely think about when programming. Existing languages that do a poor job of giving the programmer precise control over the underlying hardware, and Dahlia is a cool proposal to improve upon this. I think it's interesting think about the tradeoffs between controllability and ease of use.

**Is there a specific grad student or a project you're interested in working on?**

I'd be interested in working on anything related to programming languages or computer vision (or others)!

**Anything else you want to tell us about yourself?**

**Attach a CV if you like.**
[Resume](https://github.com/cucapra/undergrad-research/files/7073168/Richard_Wang_Resume.pdf)

**Comment by rachitnigam** [comment]
> Year in Cornell: 4th year (last sem)

Hi, @rich140! Just to clarify, do you mean that you're graduating this semester (Fall 2021)?

**Comment by rich140** [comment]
Yep, that's the plan!

**Comment by tissue3** [comment]
Hello, @rich140. I am Zhijing Li, a forth year Phd student at Capra. We are working on GPU-CPU co-optimization using MLIR this semester. If you haven't decided the project to work on and interested in the topic I just mentioned, you may contact me at zl679@cornell.edu
