### ISSUE TITLE
[Nathaniel Diamond]

### ISSUE THREAD

**Issue by NateDiamond** [cucapra/undergrad-research#7]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here is [an example](https://github.com/cucapra/undergrad-research/issues/1) of a filled out template for reference.

## Personal Details

**Name**: Nathaniel Diamond

**Major**: Computer Science

**Year in Cornell**: 2019

**Relevant classes**: CS 4160, CS 3110, CS 4780, MATH 3840 (Foundations of Mathematics), MATH 3340 (Abstract Algebra), MATH 4330 (Honors Linear Algebra). 

## Research

**When do you want to do research?**
I want to do full-time research starting September 2019 (I am graduating a year early and am taking a year to get involved in research before I apply to graduate school).

**What is exciting to you about research?**
I have always loved having projects outside of my obligations as a student. Now that I am graduating, it is exciting to think I will be able to devote myself entirely to a research project. I am excited to see what I will be able to build when I am able to focus on something intensely.

**What kind of research do you want to do?**
I am highly interested in formal methods and mathematical logic, but am very open to trying any other research that intersects mathematics and computer science. For example, in my Foundations of Mathematics course we touched on lambda calculus, and I would be very interested in diving deeper into such material.

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
I know this is a cliche answer, but [the Bitcoin Paper](https://bitcoin.org/bitcoin.pdf?) was the first academic paper that I read all the way through and understood, so it has stayed with me. I am working on reading papers in formal methods and trying to teach myself lambda calculus more formally, but this is still in the early stages.

**Is there a specific grad student or a project you're interested in working on?**
I am open to many projects, though [Opal](https://capra.cs.cornell.edu/research/opal/) definitely caught my eye. This summer I will be working with Airbnb to develop ML models for their Market team, so using that experience in a setting to design a programming language seems fascinating. If there were any projects that had a verification component, that would be amazing as well.

**Anything else you want to tell us about yourself?**
Yes! I am a lifelong learner who throws myself at whatever projects life gives me, be it my running, rock climbing, coding, or school work in mathematics. Thank you in advance for your consideration!

**Attach a CV if you like.**
[N. Diamond Resume.pdf](https://github.com/cucapra/undergrad-research/files/3129632/N.Diamond.Resume.pdf)

**Comment by sampsyo** [comment]
Hi, Nate! Thanks for getting in touch. We will get back to you if anything perfect comes up. But it sounds like you might be most excited about theoretical, mathy topics—so I have to warn you that our lab likes to focus on nitty-gritty systemsy topics with a heavy implementation (i.e., hacking) component, even when we use fancy, abstract PL topics to drive the research.

Anyway, we can definitely stay in touch, but I also want to recommend that you check out the work that other PL folks in our department are doing—for example, I bet you would enjoy talking with students who work with Ross Tate, Nate Foster, or Andrew Myers.

**Comment by NateDiamond** [comment]
Hi Professor Sampson,

     Thanks for getting back to me! I have reached out to Professors Ross Tate and Nate Foster, along with many others, and I was either dismissed or haven't been answered yet. You are the first to really engage with me about research, so I do appreciate that and would love to learn more before we say this is not a match. I do have experience with software engineering, so hacking is not a deterrent so long as it is motivated by something high-level.
     If there is anything your research group needs help with next semester that I could contribute to (either part-time or full-time), let me know. It definitely need not be a perfect fit, especially while I am still figuring out what research interests me.
     Thank you again for your consideration.

Best,
Nathaniel

**Comment by sampsyo** [comment]
OK! The way this works is that opportunities come up from time to time, and when they do and it seems like it might be a good fit, we'll let you know. So we'll be back in touch sometime when that happens.

**Comment by Checkmate50** [comment]
Hey Nate!  If you're still looking for a research project, I have a bit of an oddball project proposal.  

We've been working for the last year on the Gator language for reasoning about geometric operations, particularly in computer graphics.  We're looking to develop a game engine in Gator, both to demonstrate that we can develop a large-scale graphics project in the language and to figure out what new problems need to be tackled.

If this project sounds interesting, or if you want to hear more about Gator, let me know and I can forward you more information.  I should mention that there is some potential verification work (that might not be obvious from the project description) to be done in this direction that is hard to explain without going into more technical background.

**Comment by NateDiamond** [comment]
Hi! I would definitely be interested in hearing more about this project. I can be reached at ncd27@cornell.edu if we wanted to schedule a meeting. Also, any sort of reading about the project could be sent to me via this address. Thanks!

**Comment by Checkmate50** [comment]
Thanks for your interest!  I've send you an email with some more details.

**Comment by rachitnigam** [comment]
Hopefully this conversation led to something useful. I’m going to close this thread. @NateDiamond if you’re still looking for research positions, feel free to reopen it.
