### ISSUE TITLE
Alaia Solko-Breslin

### ISSUE THREAD

**Issue by alaiasolkobreslin** [cucapra/undergrad-research#70]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Alaia Solko-Breslin

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** First semester Master of Engineering & May 2022

**Relevant classes**: CS 2112, CS 2802, CS 3110, CS 3410, CS 4120/4121, CS 4160, CS 4410, CS 4780, CS 4814, CS 4820, CS 4830, CS 5114, CS 6110

**Interested in continuing research during the summer?** I'm not interested in doing research full time during the summer, but if there's still work I can help out with I can commit to putting in a few hours per week (maybe 10 hours/week).

**Expertise (languages/frameworks/etc.):** OCaml, Java, Python, Ruby

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.) 

Fall 2021 and Spring 2022.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)

Research is exciting to me because it's an opportunity to explore a problem where there isn't a clear solution. Even when it turns out that the problem isn't solvable, the experience of trying to reach a solution is still rewarding. I also like exploring subjects much deeper than what a class can offer to me.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")

I'm interested in programming languages research in general. But specifically I would like to do research related to compilers, program synthesis, or verification.

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

The Diospyros paper excited me because I think the problem of optimizing programs based on a specific architecture is really interesting as this problem has immediate applications. I also found the idea of a search-based compiler pretty fascinating since when it comes to compiler optimizations I've only dealt with the standard ones you learn in CS 4120.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**

I found the Diospyros and Gator projects most interesting me. I liked the Diospyros for reasons I listed above. And I liked the Gator project because I think the process of designing languages is really neat. From formalizing a language's semantics to eventually implementing a compiler just seems like a really cool process.

**Anything else you want to tell us about yourself?**

I'm doing an M.Eng. because I graduated a year early and wanted an extra year at Cornell to gain more research experience before applying to PhD programs. That's why I'm hoping to make my M.Eng. project focused on research. I would be thrilled to work in this group because I want to explore the field of programming languages and compilers even more and make sure this is the kind of work I want to do in the future.

**Attach a CV/Resumé**

[ajs644_resume.pdf](https://github.com/cucapra/undergrad-research/files/7148262/ajs644_resume.pdf)

**Comment by rachitnigam** [comment]
Hi @alaiasolkobreslin! If the [Calyx project](https://capra.cs.cornell.edu/calyx/) looks interesting to you, please email me at rnigam@cs.cornell.edu.
