### ISSUE TITLE
Obinna Abii

### ISSUE THREAD

**Issue by Obinnabii** [cucapra/undergrad-research#74]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Obinna Abii

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** Senior December 2022

**Relevant classes**: CS 3110, 3410, 4110, 4120

**Interested in continuing research during the summer?** I would love to! But I will probably not be able to give more than one credit. I expect to have an internship at the time.

**Expertise (languages/frameworks/etc.):** Java, Ocaml, JavaScript, Python, Flex, Cup

## Research

**When do you want to do research?**
 I would love to get involved during the semester as an extracurricular.

**What is exciting to you about research?**
I have been doing research in the info sci and psych departments for the past two years. I wanted to work towards solving problems in an academic space where the goal was not a grade. I enjoy learning and gaining skills from the groups I worked with. I recently took compilers and would love to use my skills in this manner. 

**What kind of research do you want to do?**
I'm looking to explore. I'm not sure at the moment but would love to explore!

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
  [Programming Language Support for Natural Language Interaction](https://mlsys.org/Conferences/2019/doc/2018/56.pdf) was a really cool paper! I'm interested in how language features can be optimized to simplify common tasks. I feel that Machine Learning and NLP are extremely common projects and support for them usually starts and stops at the package and API level. It's interesting to see a language specifically designed to remove the boilerplate involved with NLU.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
  The programming abstractions for natural language and intelligent systems. Although this project is archived, I would love to work on anything similar. I don't have much technical work this semester. I talked to Sam, a previous student at Capra, and he said he loved working there. He encouraged me to reach out!

**Anything else you want to tell us about yourself?**
I would love to help out on any projects where my knowledge of programming languages is useful. I will be here for an extra semester and would love to work with you guys!

**Attach a CV/Resumé**
[Abii_Obinna_Resume_Google_2021_fall.pdf](https://github.com/cucapra/undergrad-research/files/7392658/Abii_Obinna_Resume_Google_2021_fall.pdf)

**Comment by Checkmate50** [comment]
Hi Abii.  It's a bit late in the semester to start contributing to a project this semester, but just to clarify, will you be around next Fall?  I'm not clear from your resume and statement.

**Comment by sampsyo** [comment]
Hi, Obi—just wanted to check whether you're still interested in research! We can reopen this ticket if you're looking for something, regardless of whether it's this semester or later on.

**Comment by Obinnabii** [comment]
Hi Adrian! I am definitely still interested. I didn't see this response for some reason. I will be around next fall and am very interested in working at your lab!

**Comment by sampsyo** [comment]
Hi, @Obinnabii! If you're still looking for a project, I'm trying to start up a speculative project around hardware accelerators for computational genomics, described in https://github.com/cucapra/calyx/discussions/884. Any chance that might be interesting to you?

(I also wanted to add the qualifier that we unfortunately don't have anything exactly NLP-related going on at the moment. That Opal stuff was super fun but kind of reached a natural conclusion. Maybe someday we'll return to it!)

**Comment by sampsyo** [comment]
Obi says he's a little too busy this semester but is interested in getting involved next semester!
