### ISSUE TITLE
Liam Daniels

### ISSUE THREAD

**Issue by liamdaniels** [cucapra/undergrad-research#75]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Liam Daniels

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** Junior, graduating in 2023

**Relevant classes**: CS 3110, CS 3410, CS 4110 (currently taking) 

**Interested in continuing research during the summer?** Yes!

**Expertise (languages/frameworks/etc.):** OCaml, C, Python, Java, git, unix 

## Research

**When do you want to do research?**
I'd like to get involved in the spring, and also the summer if all goes well.

**What is exciting to you about research?**
I enjoy reasoning about programming and programming languages, especially about their readability and aesthetics. So, I would love to get some hands-on experience in PL and learn more about it. I also want to get to know and work with people who are invested in the field. More generally, the idea of thinking about and building projects for novel, open-ended problems seems appealing and fun to me, and I have heard that this is what CS research is like. I also definitely do want to "make" something using programming, if possible.

**What kind of research do you want to do?**
I'd say my interests are currently pretty broad and focused on "PL" in general. I think I'd really enjoy and learn from working on a domain-specific programming language. I am open to exploring anything, though! 

## Background

**Was there a paper that particularly excited you?**
I looked through some Capra papers, and I quite enjoyed the abridged version of [Programming Language Support for Natural Language Interaction](https://mlsys.org/Conferences/2019/doc/2018/56.pdf). I don't know much about natural language stuff, but I was sort of awestruck that a DSL could be made for something as abstract and ambiguous as NLU. The "hypothetical worlds" feature seems like a really cool idea with a wonderful name. I just love seeing programming languages applied in sort-of unexpected ways, and reading this paper makes me feel inspired to make or work on a DSL.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
I talked to Dietrich Geisler at research night a couple of days ago, and I took interest in the Caiman project. I don't know much about multi-device binding, but I do find systems-y stuff pretty intriguing when programming is also involved. I also think that graphics is an awesome application of programming languages in general.

**Anything else you want to tell us about yourself?**
I'm planning on taking Compilers next semester, so hopefully I'll have a bit more experience then.

**Attach a CV/Resumé**
[Liam_D_resume.pdf](https://github.com/cucapra/undergrad-research/files/7487604/Liam_D_resume.pdf)

**Comment by Checkmate50** [comment]
Thanks Liam for reaching out!  I'll get in touch with you over email
