### ISSUE TITLE
Anoushka Kabra

### ISSUE THREAD

**Issue by kara2703** [cucapra/undergrad-research#76]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Anoushka Kabra (ark258@cornell.edu)

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** Sophomore and Dec 2023/May 2024

**Relevant classes**: CS 2110, CS 3110, and will be taking Algo (CS 4820) in spring, CS 4700

**Interested in continuing research during the summer?**  Yes! Very interested.

**Expertise (languages/frameworks/etc.):** OCaml, Java, Python (strongest), Javascript, Swift, CSS, HTML, Django-framework, Git, Xcode

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.) 

I'm interested in getting started on research in the summer but if that is not possible, then I wouldn't mind joining Capra in Spring, and if all goes well, I'd want to explore staying at Cornell for research the coming summer.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
I had attended the ASCU Research Night and spoke with different researchers, but my interest in research I believe started from Disney. Watching Disney movies and then reading through http://graphics.pixar.com/library/. I came to Cornell to understand graphics from the mathematical and technological perspective. I believe during high school, when I had been a research intern to several firms, I was able to answer my dreading questions about computer science and it's application in industry; however, I realised that kind of research was limiting due to resources available in India for graphics and animation. 

What do I hope to get out of it? Honestly, everything. I want to be able to understand the working of Capra, the way collaboration occurs in formal research labs with computer science, the different intersection of graphics and programming language if possible (I have always been interested in graphics, artificial intelligence and computer vision!). If the research projects available to work on are not relating to graphics or computer vision, that is absolutely fine too! By working on perhaps projects such as computer architecture, I would be able to explore tangents of computer science not related to graphics and see if my interests lie somewhere else. 

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I am a very curious person, hence I would willing to explore any kind of research. However, if there are any current projects, such as Gator or Braid, I would be highly interested to work on those. As I am a sophomore, any project would work for me. But I would be interested to work with something  related to graphics, artificial intelligence and/or computer vision. 

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
I think all the research is quite exciting from Capra, however, a paper that really made me excited to join the group would be "OPTIMIZING JPEG QUANTIZATION FOR CLASSIFICATION NETWORKS" by Zhijing Li, Christopher De Sa, Adrian Sampson.
I think this paper included information on space optimisation and that interests me as it relates to reducing transfer costs for tests data, which is something similar to what I had worked on in UNF where I had tried to optimise storage of images in the database.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**

I think the most current research project I would be interested working on would be Gator or Dahlia. Dahlia is very innovative according to me as I have personally not come across several geometric accelerator design predicting languages.

**Anything else you want to tell us about yourself?**
Being part of Capra would allow me to come close to really like-minded individuals with so many different perspectives ( an ironic statement, perhaps). 

**Attach a CV/Resumé**
[resume_final_5.0.pdf](https://github.com/cucapra/undergrad-research/files/7524896/resume_final_5.0.pdf)

**Comment by Checkmate50** [comment]
Hey Anoushka,

Thanks for reaching out!  I'll message you over email if you're still interested in this position.
