### ISSUE TITLE
Adityavardhan Agrawal

### ISSUE THREAD

**Issue by Adityav369** [cucapra/undergrad-research#78]
## Personal Details

**Name**: Adityavardhan Agrawal (Adi)

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** Senior (May 2022)

**Relevant classes**: CS 2110, CS 3110, CS 4110, CS 4410

**Expertise (languages/frameworks/etc.):** C++, Python, Ocaml, IMP :)

## Research

**When do you want to do research?**
Spring 2022

**What is exciting to you about research?**
I really enjoyed CS 4110 and would love to learn more about the field of programming languages and apply it to interesting problems. I have limited research experience and would like to learn about the methodologies and processes involved in it. 

**What kind of research do you want to do?**
I am not particularly sure, but I have highlighted some Capra projects I am interested in the background section. 

## Background

**Was there a paper that particularly excited you?**
I enjoyed reading Paxos Made Moderately Complex by RVR! I learned about Paxos and the history of Paxos in my CS 5412 Cloud Computing class and how Lindsey Lamport's original paper "Paxos Made Simple" was "greek" and complex to understand. I enjoy how RVR breaks down the complex algorithm that forms the backbone of many of the important distributed software systems that exist today. 

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
I am open to work on anything. I particularly enjoyed going over Calyx and Dahlia.

**Attach a CV/Resumé**
[Adityavardhan.pdf](https://github.com/cucapra/undergrad-research/files/7847481/Adityavardhan.pdf)

**Comment by rachitnigam** [comment]
Thanks for applying! I lead the Dahlia and Calyx projects. Can you drop me an email on rnigam@cs.cornell.edu?
