### ISSUE TITLE
Pai Li

### ISSUE THREAD

**Issue by paili0628** [cucapra/undergrad-research#79]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Pai Li

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** rising junior and Dec. 2023

**Relevant classes**: CS 2110, CS 3110, CS 3410, CS 4410, CS 4820

**Interested in continuing research during the summer?** YES!

**Expertise (languages/frameworks/etc.):** Java, Python, C, OCaml, git, unix, Matlab, etc. 

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular" or get more involved over the summer, when they treat research like a full-time job.)
I would like to be involved in a research program during Spring 2022, and hopefully continue during summer.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
Having taken all the cores that the department requires, I learned about many aspects of computer science. I am deeply intrigued in some of them, specifically PL, systems, and networking, and would like to delve into these fields through research. 

I look forward to thinking about novel ideas and open-ended problems in general, which requires creativity and awareness of various details in the specific section of the project I work on. Also, with research I can gain experience with working in groups, which would require strong skills in communicating technical nuances. 

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I look forward to exploring. Anything in PL and systems would be of great interest to me.

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
I looked through some of the Capra papers and found A compiler infrastructure for accelerator generators interesting. The idea of a shared intermediate language with a compiler infrastructure to let compiler engineers design new hardware DSLs and quickly get competitive hardware design is really exciting to me. 

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
I would like to be working on Calyx or Dahlia, as I am really interested in the paper A compiler infrastructure for accelerator generators. The ideas of a shared intermediate language for building compilers (Calyx) and of affine reasoning to manage memory use (Dahlia) are exciting to me. 

**Anything else you want to tell us about yourself?**
I really hope to find passionate individuals that think alike at Capra. 

**Attach a CV/Resumé**
[Pai Li (Nina).pdf](https://github.com/cucapra/undergrad-research/files/7867315/Pai.Li.Nina.pdf)

**Comment by rachitnigam** [comment]
Hi @paili0628, I lead the Dahlia and Calyx projects. Can you email me at rnigam@cs.cornell.edu so we can follow up?
