### ISSUE TITLE
Cosmo Viola

### ISSUE THREAD

**Issue by cosmoviola** [cucapra/undergrad-research#8]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here is [an example](https://github.com/cucapra/undergrad-research/issues/1) of a filled out template for reference.

## Personal Details

**Name**: Cosmo Viola

**Major**: Computer Science and Mathematics

**Year in Cornell**: Junior

**Relevant classes**: CS 3420, CS 4160, CS 4220, CS 4410, CS 4820, CS 4850, CS 4999, CS 6110, CS 6117, CS 6815, MATH 4330 (Honors Linear Algebra), MATH 6310 (Algebra), MATH 6340 (Commutative Algebra), MATH 6510 (Algebraic Topology)

## Research

**When do you want to do research?**
I'm looking to do research during Summer 2019.

**What is exciting to you about research?**
I enjoy the process of solving problems and am excited to attack problems which are still open. I am especially interested in applications which make writing correct software easier. A large part of why I study mathematics is because I am interested in knowing when something is correct with certainty. I want to apply the same principles in CS and contribute to systems which give guarantees of correctness to programmers.

**What kind of research do you want to do?**
I am interested in ways to ensure program correctness, such as through verification in some logic or type systems, though I also would be interested in doing research in other areas.

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
This isn't a paper per say, but towards the end of CS 6117 Prof. Tate discussed a type system he worked on to ensure memory safety of programs using category theory. It was the first time I learned of a type system being used to prove a property of a program besides that it does not get stuck, and it made me interested in other potential applications of type systems for correctness.

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**
I have been doing research with Prof. Tate on inferable generics this semester. I am also interested in type theory's use in mathematics; I read the [homotopy type theory book](https://homotopytypetheory.org/book/)  over the past summer and am interested in its development as a foundation of mathematics which makes verification of proofs easier. After undergrad, I hope to pursue a PhD where I can continue doing research. Thank you for your consideration!

**Attach a CV if you like.**
[resume_cosmo_viola.pdf](https://github.com/cucapra/undergrad-research/files/3140372/resume_cosmo_viola.pdf)

**Comment by sampsyo** [comment]
Hi, Cosmo! Thanks for getting in touch. We will get back to you if anything perfect comes up. But it seems like you might be most excited about theoretical, mathy topics, especially verification—so I have to warn you that our lab likes to focus on nitty-gritty systemsy topics with a heavy implementation (i.e., hacking) component, even when we use fancy, abstract PL topics to drive the research. In particular, we don't exactly have anything verification-oriented going on at the moment, which is not to say that something won't come up in the future!

**Comment by rachitnigam** [comment]
I assume @cosmoviola will be graduating soon and isn’t looking for research opportunities. If you still are, feel free to open it. If not, good luck with everything in the future!
