### ISSUE TITLE
Alex Levinson

### ISSUE THREAD

**Issue by alexLevinson** [cucapra/undergrad-research#85]
**Note.** Before applying, make sure you can receive notifications from Github. Once you apply, make sure you're subsribed to receive emails when someone responds to the issue. We will respond to your application on Github first so it's important that you receive notifications to it and respond quickly.

We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Alex Levinson

**Major**: CS

**Year in Cornell & Expected graduation date:** Sophomore, 2024

**Relevant classes**: CS 3410, CS 3110, MATH 2210, and transfer credit equivalents for all pre-reqs

**Interested in continuing research during the summer?** Yes

**Expertise (languages/frameworks/etc.):** As it pertains to Capra & its research: Java, Python, C, RISC-V Assembly, OCaml

## Research

**When do you want to do research?**
Summer 2022

**What is exciting to you about research?**
Like a lot of CS students, I'm interested in industry, but before I sell out I want to survey all my options, and hopefully make meaningful contributions to academia along the way. I'm also intrigued by the ability to do work at the cutting edge of the fields that I'm interested in.

**What kind of research do you want to do?**
I'm a TA for CS 3410 and I really enjoy the course content, so I would like to do something related to hardware/architecture, but I'm open to exploring new topics.

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
This [article](https://ieeexplore.ieee.org/document/7948677) about storing data in DNA molecules comes to mind - I find it incredible that a group of researchers were able to store an image file in DNA and then recover it. Though they may not be practical, papers like this that push the boundaries of what is possible in computer science are thought-provoking and very interesting to read.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
CPU/GPU optimization. Compliers, parsers, and their optimization were a topic that I really enjoyed in 3410 - something about the cleverness involved to make those improvements is very intellectually challenging and appealing. I haven't had the flexibility in my class schedule to take (and everyone I have ever spoken to has warned me against taking) compilers, so working on that project could be a suitable substitute. But again, I'm open to exploring other ideas.

**Anything else you want to tell us about yourself?**
https://xkcd.com/2173/
https://xkcd.com/927/
https://upload.wikimedia.org/wikipedia/en/9/9a/Cow_Tools_cartoon.png

**Attach a CV/Resumé**
[Resume.pdf](https://github.com/cucapra/undergrad-research/files/8447116/Tech.Resume.pdf)

**Comment by Checkmate50** [comment]
Hey Alex,

Thanks for reaching out!  Would you mind sending me an email at dag368@cornell.edu so we can setup a time to chat about a potential research project?

-Dietrich
