### ISSUE TITLE
Caleb Kim 

### ISSUE THREAD

**Issue by calebmkim** [cucapra/undergrad-research#86]
**Note.** Before applying, make sure you can receive notifications from Github. Once you apply, make sure you're subsribed to receive emails when someone responds to the issue. We will respond to your application on Github first so it's important that you receive notifications to it and respond quickly.

We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Caleb Kim 

**Major**: Computer Science 

**Year in Cornell & Expected graduation date:** 2nd Year. Expected Graduation: Spring 2024 

**Relevant classes**: CS 3110, CS 3410 (currently taking), CS4810 (currently taking)

**Interested in continuing research during the summer?** Yes 

**Expertise (languages/frameworks/etc.):** 
Java, Python, OCaml. Some experience with Javascript, C, MATLAB, React.js

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular", equivalent to a 3-4 credit class, or get more involved over the summer as a full-time job.) 
I would want to start this summer, if possible (and hopefully continue into the fall). Or if that would not work out, then start in the fall. 

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
As I have gotten more experience in CS, I have noticed that I enjoy sitting down and focusing on a specific topic or project and exploring it in depth; research would be a great opportunity to do that. Up until recently, I hadn’t carefully considered what I want to do after graduation. After thinking about it more carefully, I realized that I might want to go to grad school, so I want to try research. 

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
 I’m not 100% sure yet, but I enjoyed learning about interpreters and compilers in CS3110/3410.

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
I was interested in the paper, “Dynamic witnesses for Static type Errors" (I found this paper while I was looking your examples of filled out templates). I was especially intrigued at their use of a lambda calculus for demonstrating that a program is ill-typed, and how they generated witnesses (although I was confused at parts). It was cool for me to see how it served a practical purpose to help functional programming students better understand their mistakes. 

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
Calyx. I have always been interested in how to get from higher level languages to hardware (that’s why I liked learning about compilers/ interpreters). In your paper, “A Compiler Infrastructure for Accelerator Generators”, I was interested by the discussion of the motivation behind having an intermediate language for DSL to Hardware compilers and would be interested in better understanding the details behind how Calyx works. 

**Anything else you want to tell us about yourself?**
Even though I mentioned Calyx, I am not fixed on one particular project; I would want to learn more about different projects so that I can better understand them.  

**Attach a CV/Resumé**
[CV_2022_Caleb Kim.docx](https://github.com/cucapra/undergrad-research/files/8482006/CV_2022_Caleb.Kim.docx)

**Comment by rachitnigam** [comment]
Hey @calebmkim, can you send me an email at rnigam@cs.cornell.edu so we can setup some time to chat?

**Comment by Quingsley** [comment]
Hello I am a Cs student and am currently doing research on what project to undertake in my third year which starts next month. Can your research group be of help?
