### ISSUE TITLE
Alex Ni

### ISSUE THREAD

**Issue by bananacheesepotato** [cucapra/undergrad-research#87]
## Personal Details

**Name**: Alex Ni

**Major**: Mathematics and Computer Science

**Year in Cornell & Expected graduation date**: 1st year

**Relevant classes**: CS 2110, CS 2800, MATH 2210, MATH 2220

**Interested in continuing research during the summer?**: yes

**Expertise (languages/frameworks/etc.)**: Python, Java, JavaScript; Sagemath, GAP (last 2 probably not applicable)

## Research

**When do you want to do research?**
I'd like to start during Summer 2022.

**What is exciting to you about research?**
The open-ended research questions and the sense of mystery about whether it can be solved or not. At least, contributing to the effort to solve those questions. I enjoy learning new things, especially going down rabbit holes of discovery. 

**What kind of research do you want to do?**
Anything in which I can learn something new. I especially enjoy learning about the theoretical and math intensive sides. Involving programming would be even better, simply to keep my programming skills sharp, but since it is quite late in the year, I would be very happy to partake in any sort of summer research.

## Background

**Was there a paper that particularly excited you?**
The paper on compiler optimizations (https://www.cs.cornell.edu/~kozen/Papers/opti.pdf) using Kleene Algebras excited me because it showed me the usefulness of algebraic structures in proving correctness of optimization problems. I had always thought algebra was a disconnected corner of math study, but its applicability is being discovered.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
Gator, I am interested in geometry types and especially in applications of linear algebra (matrices and transformations) in graphics. I spoke with Dietrich at research night about his latest project as well regarding the IR between CPU and GPU, and am interested in working on that too.

**Anything else you want to tell us about yourself?**
I have done research in the past, but in a completely different field (knot theory). The research involved writing code to reduce knot polynomials, which involved a lot of recursion and if-loops.

**Attach a CV/Resumé**
[Resume_Alexander_Ni_Spring2022.pdf](https://github.com/cucapra/undergrad-research/files/8502462/Resume_Alexander_Ni_Spring2022.pdf)

**Comment by Checkmate50** [comment]
Hey Alex, thanks for reaching out!

Could you send me an email at dag368@cornell.edu so we can setup a time to chat?

**Comment by Checkmate50** [comment]
I'm going to close this for the time being, but feel free to reopen if you have further information you want to share
