### ISSUE TITLE
Nathaniel Navarro

### ISSUE THREAD

**Issue by arbiter0079** [cucapra/undergrad-research#88]
**Note.** Before applying, make sure you can receive notifications from Github. Once you apply, make sure you're subsribed to receive emails when someone responds to the issue. We will respond to your application on Github first so it's important that you receive notifications to it and respond quickly.

We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Nathaniel Navarro

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** 1st year, graduate 2024

**Relevant classes**: CS 3110, ECE 2300

**Interested in continuing research during the summer?**
Very much so

**Expertise (languages/frameworks/etc.):** Java, Python, Ocaml

## Research

**When do you want to do research?**
Hope to begin summer 2022 and continue in following semesters.

**What is exciting to you about research?**
I'm excited to make meaningful discoveries that can be used to make the world more efficient, for example optimizing architectures and algorithms.
Not having much experience with research, I'd like to get my hands wet and explore what research is like in the field.

**What kind of research do you want to do?**
While my interests are broad, recently I've been interested in the idea of optimizing tasks using (possibly novel) hardware, such as the analog chips used in the presentation linked below. 

## Background

**Was there a paper that particularly excited you?**
While not a traditional research paper,
[this](https://mythic.ai/whats-new/mythic-hot-chips-2018/) presentation was of interest to me.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
I am open to anything, but am drawn towards jpeg compression and the digital signal processing work.

**Anything else you want to tell us about yourself?**
Thank you for your consideration! :)

**Attach a CV/Resumé**
[Resume](https://github.com/arbiter0079/Navarro/blob/main/Nathaniel%20Navarro%20Resume.pdf)

**Comment by rachitnigam** [comment]
Hey @arbiter0079, can you email me at rnigam@cs.Cornell.edu to setup some time to chat?
