### ISSUE TITLE
Trey Aguirre

### ISSUE THREAD

**Issue by TreyAguirre** [cucapra/undergrad-research#9]
We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here is [an example](https://github.com/cucapra/undergrad-research/issues/1) of a filled out template for reference.

## Personal Details

**Name**: Trey Aguirre

**Major**: Information Science

**Year in Cornell**: Junior (Rising Senior)

**Relevant classes**: CS 2110, CS 2800, CS 3110, CS 3152, CS 3410, CS 4154, CS 4820, CS 5152, MATH 2940

## Research

**When do you want to do research?**
I would like to start during the Summer of 2019.

**What is exciting to you about research?**
I haven't had the chance to do research so far during my time at Cornell and feel that being part of a productive research group would greatly enhance my knowledge and skills both as a computer scientist and software engineer. I like tackling new, difficult problems that I often have no prior exposure to; learning new tools, technologies and computer science concepts on a regular basis is my favorite part of software engineering so I believe that working on new and challenging research projects would be an enriching experience for me.

**What kind of research do you want to do?**
I don't have a strong preference for any particular kind of research at the moment; I want to get involved in research now so that I can figure out what specific fields interest me. However, I have been working with abstract syntax trees lately to make static analysis tools for an open source coding mentorship and practice platform called Exercism which I found quite interesting. I am also a game design minor and would be interested in research related to video games. 

## Optional Stuff

(Feel free to leave any of these blank.)

**Was there a paper that particularly excited you?**
The paper ["Bridging the gap between programming languages and hardware weak memory models"](https://dl.acm.org/citation.cfm?doid=3302515.3290382) greatly interested me when it was presented at PLDG (CS 7190) this semester. This research produced the first machine-verified compilation correctness results for memory models weaker than x86-TSO. I also enjoyed using Coq in CS 3110 so I found the researchers' use of it here to mechanize their results interesting. I would be excited to learn more about and conduct research related to formal software verification.

**Is there a specific grad student or a project you're interested in working on?**

**Anything else you want to tell us about yourself?**
I am interested in human-computer interaction, linguistics and game design in addition to computer science and software engineering. I am the maintainer for Exercism's Python track "auto-mentor" which gives users automated feedback on their submitted solutions to coding challenges. I'm also an avid paintball player.

**Attach a CV if you like.**
[Here's my resume.](https://github.com/cucapra/undergrad-research/files/3148982/trey-aguirre-resume.pdf)

**Comment by pbb59** [comment]
Hi Trey, 

My name is Phil, a grad student in Adrian's lab. We have 1-2 projects relating to computer graphics that you might be interested in. The first one is a fledgling project attempting to make real-time rendering go faster! It will primarily be an algorithm/software optimization project and you would take the lead on it (with help from us of course!). The second graphics project is being done by another grad student, but I'm not sure of the status this summer.

If you're interested in a graphics related summer project, let's set up a meeting either this week or next! We can discuss the details of the potential project then. How does your schedule look?

Thanks
-Phil

**Comment by TreyAguirre** [comment]
Hi Phil,

That sounds great! I'd definitely be interested in a graphics related summer project. I'm free to meet pretty much whenever Monday through Thursday next week.

Best,

Trey

**Comment by pbb59** [comment]
Great! How about Tuesday at 2pm? Let's meet in the Computer Systems Lab (CSL), Rhodes 471.

-Phil

**Comment by TreyAguirre** [comment]
That works for me. See you then! Best,

- Trey

**Comment by rachitnigam** [comment]
Since this thread is gone stale, I’m going to close it. @TreyAguirre if you’re still looking for research opportunities, feel free to reopen it.
