### ISSUE TITLE
Varsha Iyer

### ISSUE THREAD

**Issue by vvi2** [cucapra/undergrad-research#90]
**Note.** Before applying, make sure you can receive notifications from Github. Once you apply, make sure you're subsribed to receive emails when someone responds to the issue. We will respond to your application on Github first so it's important that you receive notifications to it and respond quickly.

We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Varsha Iyer

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** Sophomore & May 2024

**Relevant classes**: CS 2110, CS 2800, ECE 1210, CS 3110, CS 3410

**Interested in continuing research during the summer?** Yes!

**Expertise (languages/frameworks/etc.):** Python, Java, OCaml, C, JavaScript, CSS, React

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular", equivalent to a 3-4 credit class, or get more involved over the summer as a full-time job.)
I would want to get involved now - Summer 2022 - and possibly continue into the Fall 2022 semester. I am extremely flexible with my availability this summer.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)
After taking 3410, I have found that computer architecture really excites me and I am eager to explore more in the field. And I know research is a great way to explore so I'm hoping to gain a good learning experience, maybe a new career goal, and a chance to meet new people and mentors. I am also thinking about grad school, so getting involved in research may help me with that decision too.
**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
As I mentioned before, CS 3410 has significantly piqued my interest in computer architecture and I can genuinely say I've enjoyed completing all the projects for the class, especially simulating the RISC-V interpreter in C. I really enjoy coding, so the intersection of software and designing hardware would be an ideal research area. 

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)
The paper describing Calyx titled "A Compiler Infrastructure for Accelerator Generators" was super interesting! The way Calyx intermediate language was designed to consist of 'components' that then instantiate 'cells' and 'wires' and finally 'control' code to assign execution schedules by encapsulating them in groups - it's so cool how Calyx can so meticulously model hardware and control their behavior. It was also exciting to see the use of FSMs in the Calyx compiler to keep track of states in the process of reducing the component's control program to a single group enable. Furthermore, in the building of the Calyx-based compiler for Dahlia, it was so cool to see the one-to-one mapping between the Calyx backend constructs to the language constructs in lowered Dahlia. Finally, reading about the plan to design a specific Calyx operator for enabling frontends to instantiate pipelining, makes me really excited to see the future of this project!
**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
I'd be interested in Dahlia! A frontend programming language used for analyzing high level synthesis designs and their efficiency in being implemented as hardware, perfectly describes the intersection of software and hardware. I really want to learn more about Dahlia and what is involved in designing a programming language aimed at reducing pitfalls in hardware design.
**Anything else you want to tell us about yourself?**
I'm an extremely curious person and I love learning and trying new things. Reading about CAPRA projects really excites me and I am eager to learn more about them!
**Attach a CV/Resumé**
[resume_pdf.pdf](https://github.com/cucapra/undergrad-research/files/8568445/resume_pdf.pdf)

**Comment by rachitnigam** [comment]
Hey @vvi2, can you email me at rnigam@cs.cornell.edu to setup a time to chat?

**Comment by avanhatt** [comment]
Hey @vvi2! We also have some compiler-focused potential projects available related to verification of a domain-specific language for instruction lowering. This would be for starting this summer. If you're interested, email me at avh@cs.cornell.edu, thanks!
