### ISSUE TITLE
[Meredith Hu]

### ISSUE THREAD

**Issue by meredithmhu** [cucapra/undergrad-research#91]
**Note.** Before applying, make sure you can receive notifications from Github. Once you apply, make sure you're subsribed to receive emails when someone responds to the issue. We will respond to your application on Github first so it's important that you receive notifications to it and respond quickly.

We are thrilled that you're interested in research in our research group! Please fill out this issue template. When you submit it, we will get a notification in our group chat. Please include any relevant details you can think of! Here are [examples](https://github.com/cucapra/undergrad-research/issues?q=is%3Aissue+is%3Aopen+label%3AExample) of filled out templates for reference.

For active projects in our group, take a look at our [group website](https://capra.cs.cornell.edu/).

## Personal Details

**Name**: Meredith Hu

**Major**: CS

**Year and Expected Graduation Date:** Junior, graduating December 2024

**Relevant Coursework**: CS 4160, CS 3110, MATH 4710, INFO 2950, Systems (not at Cornell), Graphics (not at Cornell)

**Interested in continuing research over the summer?**: Yes!

**Expertise (languages/frameworks/etc.):** Enough C, Coq, OCaml, Python, Git, Bash for class projects. Enough React, React Native Web, JS, Node, to contribute to a web app. Some Java (not much).

## Research

**When do you want to do research?**
This summer. I'd be happy to continue longer too.

**What is exciting to you about research?**
I recently got dropped an opportunity to be funded with a research stipend, as long as I found a faculty member or grad student this week whose research agenda I could help with. This term, I tried my hand out at software development on an app development team. I took CS 4160 at the same time, and I had more fun there. The intent behind research seems to be exploring questions rather than creating a product. I enjoy asking about things like the choices Coq makes or the mathematical framework the code represents, and my favorite conversations are those I have about the reasoning of these languages. I guess in that way, I started thinking research might make sense as the next step in my CS journey. It truly sounds so fun. And I'd love to get involved.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")
I like FV, PL, functional programming, and systems. Math is very charming. I wouldn't mind doing some. This summer though, any project, topic, and time, even coding very simple or manually laborious tasks, is completely welcome.

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
I tried reading a few from Capra, but I find I don't know enough PL. [This paper I found on the website](https://mlsys.org/Conferences/2019/doc/2018/56.pdf) looked interesting because I have a lot of background in Latin and most people are always telling me to get into something involving language processing. Studying Latin does give me perspective on that. For example, I agree that language is very context-dependent and user intent for the same words can greatly vary. I love type theory, so I love it when someone wants to solve a problem with a type-directed approach. And so this paper is a really great marriage of those two interests of mine.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
I'm interested in anything and have no preference. If forced to pick something, maybe Gator? Writing transformational code with geometry types sounds like the type of programming we do in 4160, and I've coded animated graphics before. I also wouldn't mind exploring compilers and math more.

**Anything else you want to tell us about yourself?**
I actually have a lot of Classics background. I can translate Latin, so I would be pretty good at naming new Capra projects. Jokes aside, it made me a better developer since it gave me unorthodox ideas, and I think it would help in research, because it's taught me exploratory thinking. It also gives me perspective on linguistics. 

**Attach a CV/Resumé**
[Meredith_Hu_CS_Resume.pdf](https://github.com/cucapra/undergrad-research/files/8643334/Meredith_Hu_CS_Resume.pdf)

**Comment by Checkmate50** [comment]
Hey Meredith,

Thanks for reaching out!  Could you reach out to me at dag368@cornell.edu so we could setup a time to meet?
