### ISSUE TITLE
Andy Pang

### ISSUE THREAD

**Issue by andypang1010** [cucapra/undergrad-research#95]
### **Personal Details**
**Name**: Andy Pang
**Major**: Computer Science
**Minor**: Physics
**Year in Cornell**: 2nd Year
**Relevant Classes**: CS 2110, CS 2800, CS 3110, CS 4780, MATH 1920, MATH 2110
**Skills**: Python, Java, OCaml, NumPy, JavaScript, C#

### **Research**
**When do you want to do research?**
I would like to start as soon as possible. I hope to begin this Fall, but Spring 2023 would also be okay.

**What is exciting to you about research?**
I've never done research before and the idea of tackling problems on a topic that isn't solved yet fascinates me as we are constantly making progress and leaving an impact on those that come after us. I would like to work under an academically rigorous research team to explore my interest in what I might like to focus on in the future. and also build skills, both technical and interpersonal, that are going to be cru

**What kind of research do you want to do?**
I am very interested in researching the potential applications of the Gator language as well as ways we can compress JPEG images for ML purposes.

### **Optional Stuff**
**Was there a paper that particularly excited you?**
I read the "Geometry Types for Graphics Programming" paper and I am fascinated by building a graphics programming language on top of GLSL that improves the performance and accuracy of the rendering without sacrificing much of the efficiency of the program. It really blew my mind how much potential this has in real-world problems when applied to engines like Blender and Unity.

**Is there a specific grad student or a project you're interested in working on?**
I chatted with Dietrich on his current projects, including CPU GPU Optimization, and the Caiman project on PL, but mostly about his Gator project for Geometric Types. I would love to work with him on any of his projects.

**Anything else you want to tell us about yourself?**
I am a fast learner and I am eager to learn anything thrown at me.

Attach a CV if you like.
[Andy Pang's Resume.pdf](https://github.com/cucapra/undergrad-research/files/9721531/Andy.Pang.s.Resume.pdf)

**Comment by sampsyo** [comment]
Reopening this as we enter the new semester, just in case something obvious crops up. @andypang1010, are you still interested in research?

**Comment by andypang1010** [comment]
Yeah, I'm definitely still interested in CAPRA! In particular, I'm inclined towards CAIMAN with Dietrich.
