### ISSUE TITLE
John Rubio

### ISSUE THREAD

**Issue by JohnDRubio** [cucapra/undergrad-research#96]
**Name**: John Rubio

**Major**: Computer Science

**Year in Cornell & Expected graduation date:** 1st year **M.S.** & May 2024

**Relevant classes**: CS 3410, CS 5410, CS 5411

**Interested in continuing research during the summer?** Yes

**Expertise (languages/frameworks/etc.):** C, C++, RISC-V

## Research

**When do you want to do research?**
(Researchers can get involved during the semester as an "extracurricular", equivalent to a 3-4 credit class, or get more involved over the summer as a full-time job.)

I would like to get started with research in the Spring 2023 semester.

**What is exciting to you about research?**
(How did you get interested in it? What are you hoping to get out it?)

Given the slow-down of Moore's Law, I'm excited to contribute to the advancements in computing in new and creative ways. Specifically, I'm excited to help build tools for designing domain-specific hardware accelerators.

**What kind of research do you want to do?**
(It's OK to say, "I don't know; I'm looking to explore!")

I'm not sure yet. I'm interested in several projects going on in this lab such as Calyx and helping with its infrastructure, possible applications of Calyx, Dhalia, verification of compiler backends, etc.

## Background

**Note**: While these questions are optional for first & second year students, we highly encourage everyone to respond to them. Third & fourth year students are required to respond to all questions.

**Was there a paper that particularly excited you?**
(This doesn't have to be a paper from our group.)

*MLIR: Scaling Compiler Infrastructure for Domain Specific Computation* [(link)](https://ieeexplore.ieee.org/abstract/document/9370308?casa_token=iWTCDC3cveAAAAAA:0KN5-8zBYd0On5e3wOz92dQNg8TISfxlzFrx8apX28pihFeIrkwHbb6szlGaPStDbf0JDasS) was a paper I found particularly exciting. One area I am interested in is how compilers and compiler infrastructures can be leveraged for optimizing machine learning applications. MLIR is an example of one such infrastructure. An interesting use case for MLIR is machine learning workflows such as TensorFlow. In the paper, MLIR showed an ability to generate uniform, consistent intermediate representations which were used to optimize the execution of the TensorFlow workload.

C. Lattner et al., "MLIR: Scaling Compiler Infrastructure for Domain Specific Computation," 2021 IEEE/ACM International Symposium on Code Generation and Optimization (CGO), 2021, pp. 2-14, doi: 10.1109/CGO51591.2021.9370308.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**

I am a bit torn on this because I'm interested in working on both Calyx and Dhalia. Calyx because I find the problem of creating an intermediate language for compiling domain-specific languages to hardware fascinating. Dhalia because in a post-Moore's Law world,  hardware accelerators are becoming increasingly important, therefore accelerator design languages are also becoming increasingly important and I would love to learn more about them.

**Anything else you want to tell us about yourself?**

1. I just want to note that I am a grad student in the M.S. CS program. I spoke with Professor Sampson before filling out this application so I just wanted to let you know that I didn't mistakenly fill out the undergraduate application.

2. I am relatively new to computer science. I spent the first 2 years of my bachelor's degree studying Statistics before taking my first computer science course, but once I did I was hooked. 

3. I was inspired to get involved in research after watching Patterson & Hennessey's 2017 Turing Award Lecture. Specifically, I was inspired by their discussion of domain-specific hardware and compilers. [(link)](https://www.acm.org/hennessy-patterson-turing-lecture)

**Attach a CV/Resumé**
[Resume_John Rubio_Fall 2022.pdf](https://github.com/cucapra/undergrad-research/files/9845166/Resume_John.Rubio_Fall.2022.pdf)

**Comment by rachitnigam** [comment]
Hey @JohnDRubio! I'm one of the leads for the Dahlia and Calyx projects. Can you send me an email at rnigam@cs.cornell.edu so we can set up some time to chat your application?
