### ISSUE TITLE
Becky Hu

### ISSUE THREAD

**Issue by Becky-Hu-82** [cucapra/undergrad-research#98]
## Personal Details

**Name**: Becky Hu

**Major**: computer science

**Year in Cornell & Expected graduation date**: senior, expected to graduate in May 2023

**Relevant classes**: CS 4620, CS 4670, CS 5625, CS 6630, CS 3410, CS 4410

**Interested in continuing research during the summer?**: yes

**Expertise (languages/frameworks/etc.)**: python, C++ with OpenGL and PBRT, Javascript with Three.js, Java, Golang

## Research

**When do you want to do research?**: winter 2022 - summer 2022

**What is exciting to you about research?**
Two of my areas of interest are graphics and systems. I've done projects that used deferred shading pipeline (using C++ and OpenGL) to render a Chinese watercolor styled scene (a screenshot is attached below). I'm also doing work related to path tracing right now. Meanwhile my past internships have been about systems and I have read some papers about system designs out of personal interest. I was hoping to better integrate these two areas in this research experience, especially in terms of system support for speeding up graphics rendering.
![image](https://user-images.githubusercontent.com/60638132/203577817-974eec87-9dca-4234-9196-e84d63bd4dac.png)

**What kind of research do you want to do?**
The two general topics I can think of are either digging more into shading languages or exploring hardware-software supports that can speed up Monte-Carlo based ray / path tracers, but I'm open to explore other interesting topics on the intersections of graphics and systems.

## Background

**Was there a paper that particularly excited you?**
[A real-time procedural shading system for programmable graphics hardware](https://dl.acm.org/doi/10.1145/383259.383275)
This paper discusses a shading language systems that can provide a reasonable level of abstraction for real time shading. It is interesting to me because I only started to look into the intersection of graphics and systems after I went to a talk given by one of the authors and had thus started to look into his papers. This paper is already decades old and I look forward to exploring more about how the technology has evolved in the past few years both on myself and hopefully in the research group.

**Which of the [current research projects](https://capra.cs.cornell.edu/) would you be interested in working on and why?**
Gator and Braid both look interesting because they probe into the intersection of graphics and systems which is exactly what I'm interested in. I'm taking compilers next semester so I may even understand the technical details more in a few months.

**Anything else you want to tell us about yourself?**

**Attach a CV/Resumé**
[Resume](https://github.com/cucapra/undergrad-research/files/10097455/Becky.Hu.Resume.2022.1.pdf)

**Comment by rachitnigam** [comment]
Hey @Becky-Hu-82! Super cool stuff. I'm one of the graduate students leading the hardware acceleration projects in the lab. Just a couple of clarifying questions: you mentioned you're planning to graduate in May '23 so I assume you can't continue on research after that in the summer (your application currently says you'd be interested in doing so)?

**Comment by Becky-Hu-82** [comment]
> Hey @Becky-Hu-82! Super cool stuff. I'm one of the graduate students leading the hardware acceleration projects in the lab. Just a couple of clarifying questions: you mentioned you're planning to graduate in May '23 so I assume you can't continue on research after that in the summer (your application currently says you'd be interested in doing so)?

Hi Rachit, thanks for the quick reply! It's right that I'm graduating next spring, but I will be able to continue over the summer. Basically I'm gonna go to the industry after my graduation but I plan to apply to graduate schools in the future. To this end, I'm willing to stay over the summer for research both so that I can have more experiences that can better prepare me for grad applications and that I can show you guys my determination to work something out though being a graduating senior. Also my work would only start in September which gives me time to stay over the summer (I mentioned more details about my post-graduation plans with Adrian). Let me know if this has cleared some of your questions!

**Comment by rachitnigam** [comment]
Okay! Thanks for clarifying. One potential project that could be interesting is building some hardware to accelerate image processing computation. If you're interested, feel free to reach out to me at rnigam@cs.cornell.edu to setup some time to chat!
